GlobalParameters:
  BoundsCheck: False
  KernelTime: True
  NewClient: 2
  NumBenchmarks: 20
  NumElementsToValidate: 128

  
BenchmarkProblems:

  ########################################
  # NT
  ########################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: d
      TransposeA: False
      TransposeB: True
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - BufferLoad: [True]
        - BufferStore: [True]
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - WorkGroupMapping: [8]
      ForkParameters:
        - VectorWidth: [2]        
        - PersistentKernel: [0,4,64,120]
        - PrefetchLocalRead: [0,1]
        - PrefetchGlobalRead: [True,False]
        - InnerUnroll: [1,2]
        - ThreadTile:
          - [ 2, 4 ]          
        - WorkGroup:
          - [ 16, 8, 1 ]   # 32x32
          - [ 16, 8, 2 ]   # 32x32, LSU=2
        - DepthU: [8,16]
        - StaggerU: [16,32]
        - StaggerUStride: [128]      
        - StaggerUMapping: [1]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          # - Exact: [ 32, 4096, 1, 32, 32, 32, 32, 4096 ] # padding = 0
          - Exact: [ 32, 4096, 1, 32, 32, 32, 32, 4160 ] # padding = 64       # this shows best eff
          # - Exact: [ 32, 4096, 1, 32, 32, 32, 32, 4224 ] # padding = 128                  
          # - Exact: [ 32, 8192, 1, 32, 32, 32, 32, 8192 ] # padding = 0
          # - Exact: [ 32, 8192, 1, 32, 32, 32, 32, 8256 ] # padding = 64
          - Exact: [ 32, 8192, 1, 32, 32, 32, 32, 8320 ] # padding = 128     # this shows best eff
          # - Exact: [ 32, 12288, 1, 32, 32, 32, 32, 12288 ] # padding = 0     
          - Exact: [ 32, 12288, 1, 32, 32, 32, 32, 12352 ] # padding = 64     
          # - Exact: [ 32, 12288, 1, 32, 32, 32, 32, 12416 ] # padding = 128     
          - Exact: [ 32, 16384, 1, 32, 32, 32, 32, 16384 ] # padding = 0     # this shows best eff
          # - Exact: [ 32, 16384, 1, 32, 32, 32, 32, 16448 ] # padding = 64     
          # - Exact: [ 32, 16384, 1, 32, 32, 32, 32, 16512 ] # padding = 128               
          # - Exact: [ 32, 20480, 1, 32, 32, 32, 32, 20480 ] # padding = 0
          # - Exact: [ 32, 20480, 1, 32, 32, 32, 32, 20544 ] # padding = 64
          - Exact: [ 32, 20480, 1, 32, 32, 32, 32, 20608 ] # padding = 128    # this shows best eff
          # - Exact: [ 32, 24576, 1, 32, 32, 32, 32, 24576 ] # padding = 0
          # - Exact: [ 32, 24576, 1, 32, 32, 32, 32, 24640 ] # padding = 64
          - Exact: [ 32, 24576, 1, 32, 32, 32, 32, 24704 ] # padding = 128    # this shows best eff
          # - Exact: [ 32, 28672, 1, 32, 32, 32, 32, 28672 ] # padding = 0
          # - Exact: [ 32, 28672, 1, 32, 32, 32, 32, 28736 ] # padding = 64
          - Exact: [ 32, 28672, 1, 32, 32, 32, 32, 28800 ] # padding = 128    # this shows best eff
          # - Exact: [ 32, 32768, 1, 32, 32, 32, 32, 32768 ] # padding = 0
          # - Exact: [ 32, 32768, 1, 32, 32, 32, 32, 32832 ] # padding = 64
          - Exact: [ 32, 32768, 1, 32, 32, 32, 32, 32896 ] # padding = 128    # this shows best eff

LibraryLogic:

   ScheduleName: "arcturus"
   DeviceNames: ["Device 7380", "Device 7388", "Device 738c", "Device 7390"]
   ArchitectureName: "gfx908"

LibraryClient:
