GlobalParameters:
  NumElementsToValidate: 128
  KernelTime: True
  DataInitTypeAlpha: 1
  DataInitTypeBeta: 0
  MaxWorkspaceSize: 33554432

BenchmarkProblems:
  ########################################
  # NN - standard
  ########################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: h
      # DestDataType: B
      # ComputeDataType: s
      HighPrecisionAccumulate: True
      TransposeA: False
      TransposeB: False
      UseBeta: True
      Batched: True
    - # BenchmarkProblemSizeGroup - Standard - All problem
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
      ForkParameters:
        - MatrixInstruction:
          - [32, 32, 8, 1,  1,  1,1,  2,2]  # 64x64
          - [32, 32, 8, 1,  1,  1,2,  2,2]  # 64x128
          - [32, 32, 8, 1,  1,  1,4,  2,2]  # 64x256
          - [32, 32, 8, 1,  1,  2,1,  2,2]  # 128x64
          - [32, 32, 8, 1,  1,  2,2,  2,2]  # 128x128
          - [32, 32, 8, 1,  1,  2,4,  2,2]  # 128x256
          - [32, 32, 8, 1,  1,  4,1,  2,2]  # 256x64
          - [32, 32, 8, 1,  1,  4,2,  2,2]  # 256x128
          - [32, 32, 8, 1,  1,  4,4,  2,2]  # 256x256
          - [16, 16, 16, 1,  1,  1,1,  2,2] # 32x32
          - [16, 16, 16, 1,  1,  1,2,  2,2] # 32x64
          - [16, 16, 16, 1,  1,  2,1,  2,2] # 64x32

          # Specialized MT
          - [32, 32, 8, 1,  1,  1,3,  4,1]  # 128x96
          - [32, 32, 8, 1,  1,  3,1,  1,4]  # 96x128
          - [32, 32, 8, 1,  1,  1,9,  4,1]  # 128x288
          - [32, 32, 8, 1,  1,  9,1,  1,4]  # 288x128
          - [32, 32, 8, 1,  1,  1,5,  4,1]  # 128x160
          - [32, 32, 8, 1,  1,  5,1,  1,4]  # 160x128
          - [32, 32, 8, 1,  1,  2,5,  4,1]  # 256x160
          - [32, 32, 8, 1,  1,  5,2,  1,4]  # 160x256

          - [16, 16, 16, 1,  1,  3,3,  2,2] # 96x96
          - [16, 16, 16, 1,  1,  5,5,  2,2] # 160x160

          - [16, 16, 16, 1,  1,  2,9,  4,1] # 128x144
          - [16, 16, 16, 1,  1,  9,2,  1,4] # 144x128
          - [16, 16, 16, 1,  1,  4,9,  4,1] # 256x144
          - [16, 16, 16, 1,  1,  9,4,  1,4] # 144x256
        - ThreadTile:
          - [ 1, 32 ]
        - WorkGroup:
          - [ 64, 4, 1 ]
        - AssertFree0ElementMultiple: [8]
        - PrefetchGlobalRead: [1]
        - PrefetchLocalRead: [2,5,9]
        - DepthU: [32,64]
        - VectorWidth: [2]
        - GlobalReadVectorWidth: [2,4,8]
        - LocalReadVectorWidth: [8]
        - SuppressNoLoadLoop: [0]
        - OptNoLoadLoop: [1]
        - ScheduleLocalWrite: [1]
        - ScheduleGlobalRead: [1]
        - ScheduleIterAlg: [3]
        - InnerUnroll: [1]
        - ExpandPointerSwap: [1]
        - TransposeLDS: [1]
        - LdsBlockSizePerPad: [-1]
        - LdsPadA: [-1]
        - LdsPadB: [-1]
        - StoreRemapVectorWidth: [-1]
        # - StaggerUMapping: [0,3]
        - StaggerUStride: [128,256]
        - StaggerU: [0,32]
        - WorkGroupMapping: [1,2,15]
        - WaveSeparateGlobalReadA: [1]
        - WaveSeparateGlobalReadB: [1]
        - 1LDSBuffer: [0,1]
        - GlobalSplitU: [1,2,3,5,7,15]
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Exact: [ 4096, 4096, 1, 4096 ] #gemm
          
LibraryLogic:
    ScheduleName: "arcturus"
    DeviceNames: ["Device 7380", "Device 7388", "Device 738c", "Device 7390"]
    ArchitectureName: "gfx908"

LibraryClient:
