GlobalParameters:
  MinimumRequiredVersion: 4.4.0
  PrintLevel: 1
  ForceRedoBenchmarkProblems: True
  ForceRedoLibraryLogic: True
  ForceRedoLibraryClient: True
  CMakeBuildType: Release
  EnqueuesPerSync: 5
  SyncsPerBenchmark: 3
  LibraryPrintDebug: False
  NumElementsToValidate: 128
  ValidationMaxToPrint: 4
  ValidationPrintValids: False
  ShortNames: False
  MergeFiles: False
  Platform: 0
  Device: 0
  KernelTime: True
  PinClocks: False # Must be set to False.
  SleepPercent: 0
  DataInitTypeBeta : 0
  PrintSolutionRejectionReason: True # Route rejected configs to std out.
  PrintWinnersOnly: 0

BenchmarkProblems:
  ########################################
  # NN - standard
  ########################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: False
      TransposeB: False
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - standard
      InitialSolutionParameters:
      # Empty for simplicity. 
      # Please see https://github.com/ROCmSoftwarePlatform/Tensile/wiki/Benchmark-Protocol
      # for a detailed explanation.
      BenchmarkCommonParameters:
      # Specify parameters that are to be considered "determined"
      # prior to kernel forking.
        - ProblemSizes:
          - Exact: [1024, 1024, 1, 512]
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
      ForkParameters:
      # The following parameters are forked on because they often have an
      # outsized impact on the performance of a kernel for a given problem 
      # and a given macro tile.
        - PrefetchLocalRead: [False, True]
        - PrefetchGlobalRead: [False, True]
        - ThreadTile:
          - [2, 2]
          - [4, 4]
        - WorkGroup:
          - [16, 16, 1]
          - [8, 8, 4]
        - WorkGroupMapping: [1, 4]
        - TransposeLDS: [0, 1]
        - LdsBlockSizePerPad: [-1, 0, 64]
        - DepthU: [4, 8]
        - StoreVectorWidth: [-1, 1, 2, 4]
      BenchmarkForkParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
        # Specify the dimensions of the problems that the forked kernels
        # should be evaluated on.
          - Range: [ [128, 128, 128, 1408], [128, 128, 128, 1408], [1], [256, 512, 512, 2048] ]

# Specify appropriate parameters for your target device.
LibraryLogic:
  ScheduleName: "navi21"
  ArchitectureName: "gfx1030"
LibraryClient:
