GlobalParameters:
  BoundsCheck: False
  KernelTime: True
  NewClient: 2
  # PrintSolutionRejectionReason: True
  # NumElementsToValidate: 65535
  # CMakeBuildType: Debug

BenchmarkProblems:

  ########################################
  # NN
  ########################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: d
      TransposeA: False
      TransposeB: False
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - BufferLoad: [True]
        - BufferStore: [True]
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - WorkGroupMapping: [8]
      ForkParameters:
        - VectorWidth: [2]          # 4 never wins
        - ThreadTile:
          - [ 2, 4 ]
        - WorkGroup:
          - [ 32, 2, 1 ]  # 64x8
          - [ 16, 4, 1 ]  # 32x16
          - [ 16, 8, 1 ]  # 32x32
        - DepthU: [8,16,32]
        # - DepthU: [8]
        - StaggerU: [0]
        - StaggerUStride: [256]
        - StaggerUMapping: [0]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [33554432], [32], [1], [32] ]  # strideA = 33554432, should fail on DU >= 16 (For tensorA-N) # MT32x32x8: PassBufferLoadAssert but FailBufferStoreAssert
          - Range: [ [16777216], [32], [1], [32] ]  # strideA = 16777216, should fail on DU >= 32 (For tensorA-N) # MT32x32x8/MT32x32x16: PassBufferLoadAssert but FailBufferStoreAssert
          - Range: [ [32], [32], [1], [33554432] ]  # strideB = 33554432, should fail on MT1 >= 16 (For tensorB-N)
          - Range: [ [32], [32], [1], [16777216] ]  # strideB = 16777216, should fail on MT1 >= 32 (For tensorB-N)

  ########################################
  # NT
  ########################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: d
      TransposeA: False
      TransposeB: True
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - BufferLoad: [True]
        - BufferStore: [True]
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - WorkGroupMapping: [8]
      ForkParameters:
        - VectorWidth: [2]          # 4 never wins
        - ThreadTile:
          - [ 2, 2 ]
        - WorkGroup:
          - [ 8, 8, 1 ]  # 16x16
          - [ 8, 16, 1 ]  # 16x32
          - [ 16, 8, 1 ]  # 32x16
        - DepthU: [8,16,32]
        # - DepthU: [8,16]
        - StaggerU: [0]
        - StaggerUStride: [256]
        - StaggerUMapping: [0]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [33554432], [32], [1], [32] ]  # strideA = 33554432, should fail on DU >= 16 (For tensorA-N) # DU8: PassBufferLoadAssert but FailBufferStoreAssert
          - Range: [ [16777216], [32], [1], [32] ]  # strideA = 16777216, should fail on DU >= 32 (For tensorA-N) # MT16x32x8 / MT16x32x16: PassBufferLoadAssert but FailBufferStoreAssert
          - Range: [ [32], [33554432], [1], [32] ]  # strideB = 33554432, should fail on DU >= 16 (For tensorB-T)
          - Range: [ [32], [16777216], [1], [32] ]  # strideB = 16777216, should fail on DU >= 32 (For tensorB-T)

  ########################################
  # TN
  ########################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: d
      TransposeA: True
      TransposeB: False
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - BufferLoad: [True]
        - BufferStore: [True]
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - WorkGroupMapping: [8]
      ForkParameters:
        - VectorWidth: [2]          # 4 never wins
        - ThreadTile:
          - [ 2, 2 ]
        - WorkGroup:
          - [ 4, 4, 4 ]   # 8x8x4
          - [ 4, 8, 2 ]   # 8x16x2
          - [ 8, 4, 2 ]   # 16x8x2
          - [ 8, 8, 1 ]   # 16x16
          - [ 8, 16, 1 ]  # 16x32
          - [ 16, 8, 1 ]  # 32x16
        - DepthU: [16]      # DU doesn't affect bufferload limit in TN
        - StaggerU: [0]
        - StaggerUStride: [256]
        - StaggerUMapping: [0]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [32], [32], [1], [33554432] ]  # strideA = 33554432, should fail on MT0 >= 16 (For tensorA-T)  # strideB = 33554432, should fail on MT1 >= 16 (For tensorB-N)
          - Range: [ [32], [32], [1], [16777216] ]  # strideA = 16777216, should fail on MT0 >= 32 (For tensorA-T)  # strideB = 16777216, should fail on MT1 >= 32 (For tensorB-N)

  ########################################
  # TT
  ########################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: d
      TransposeA: True
      TransposeB: True
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - BufferLoad: [True]
        - BufferStore: [True]
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - WorkGroupMapping: [8]
      ForkParameters:
        - VectorWidth: [2]          # 4 never wins
        - ThreadTile:
          - [ 2, 2 ]
        - WorkGroup:
          - [ 4, 4, 4 ]   # 8x8
          - [ 8, 4, 2 ]   # 16x8
          - [ 16, 4, 1 ]  # 32x8
        - DepthU: [8,16,32]
        - StaggerU: [0]
        - StaggerUStride: [256]
        - StaggerUMapping: [0]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [32], [32], [1], [33554432] ]  # strideA = 33554432, should fail on MT0 >= 16 (For tensorA-T)
          # - Range: [ [32], [32], [1], [16777216] ]  # strideA = 16777216, should fail on MT0 >= 32 (For tensorA-T)  # TODO - this randomly causes a segfault, Skip for now
          - Range: [ [32], [33554432], [1], [32] ]  # strideB = 33554432, should fail on DU >= 16 (For tensorB-T)
          - Range: [ [32], [16777216], [1], [32] ]  # strideB = 16777216, should fail on DU >= 32 (For tensorB-T)

LibraryLogic:
    ScheduleName: "vega20"
    DeviceNames: ["Device 66a0", "Device 66a1", "Device 66a7", "Device 66af", "Vega 20"]
    ArchitectureName: "gfx906"

    ScheduleName: "arcturus"
    DeviceNames: ["Device 7380", "Device 7388", "Device 738c", "Device 7390"]
    ArchitectureName: "gfx908"

LibraryClient:
