GlobalParameters:
  MinimumRequiredVersion: 4.4.0
  PrintLevel: 1
  ForceRedoBenchmarkProblems: True
  ForceRedoLibraryLogic: True
  ForceRedoLibraryClient: True
  CMakeBuildType: Release
  EnqueuesPerSync: 1
  SyncsPerBenchmark: 1
  LibraryPrintDebug: False
  NumElementsToValidate: 10
  ValidationMaxToPrint: 4
  ValidationPrintValids: False
  ShortNames: False
  MergeFiles: True
  Platform: 0
  Device: 0
  KernelTime: True
  PinClocks: False
  SleepPercent: 200
  DataInitTypeBeta : 0
  DataInitTypeAlpha: 1
  DataInitTypeA: 3
  DataInitTypeB: 3
  DataInitTypeC: 6
  DataInitTypeD: 6
  PrintTensorA: 0
  PrintTensorB: 0
  PrintTensorC: 0
  PrintTensorD: 0

BenchmarkProblems:
  ########################################
  # NT - standard
  ########################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: B
      DestDataType: B
      ComputeDataType: s
      HighPrecisionAccumulate: True
      TransposeA: True
      TransposeB: False
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - PrefetchLocalRead: [True]
      ForkParameters:
        - PrefetchGlobalRead: [True]
        - ThreadTile:
          - [ 4, 8 ]
        - WorkGroup:
          - [ 16, 16, 1 ]
        - WorkGroupMapping: [8]
        - GlobalSplitU: [1]
        - DepthU: [32]
        - VectorWidth: [-1]
        - AssertSummationElementMultiple: [8]
        - AssertFree0ElementMultiple: [8]
        - ReplacementKernel: [True]
      BenchmarkForkParameters:
      JoinParameters:
        - MacroTile
        - GlobalSplitU
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Exact: [ 1024,1024,1,1024 ]

#  ########################################
#LibraryLogic:
#    ScheduleName: "vega20"
#    DeviceNames: ["Device 66a0", "Device 66a1", "Device 66a7", "Vega 20"]
#    ArchitectureName: "gfx906"
#
##   ScheduleName: "vega10"
##   DeviceNames: ["Device 6863", "Device 6862", "Device 687f", "Device 6860", "Device 6861", "Vega 10 XTX [Radeon Vega Frontier Edition]", "Vega [Radeon RX Vega]",
##      Vega, Device 6864, Device 686c]
##   ArchitectureName: "gfx900"
#
##   ScheduleName: "mi25"
##   DeviceNames: ["Device 6860"]
##   ArchitectureName: "gfx900"
#
##   ScheduleName: "r9nano"
##   DeviceNames: ["Device 7300"]
##   ArchitectureName: "gfx803"
#
##   ScheduleName: "hip"
##   DeviceNames: ["Device 0000"]
##   ArchitectureName: "fallback"
#
#LibraryClient:

