GlobalParameters:
  BoundsCheck: False
  KernelTime: True
  NewClient: 2
  PrintSolutionRejectionReason: True

BenchmarkProblems:

  ########################################
  # NN / TLUA = 1, TLUB = 0
  ########################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: d
      TransposeA: False
      TransposeB: False
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - BufferLoad: [True]
        - BufferStore: [True]
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - WorkGroupMapping: [8]
      ForkParameters:
        - VectorWidth: [2]
        - ThreadTile:
          - [ 2, 4 ]
        - WorkGroup:
          - [ 16, 8, 1 ]  # 32x32
        - DepthU: [16,32]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [16777216], [16], [1], [16] ]  # strideA = 16777216, should fail on DU >= 32 (For tensorA-N)
          - Range: [ [16], [16], [1], [16777216] ]  # strideB = 16777216, should fail on MT1 >= 32 (For tensorB-N)

  ########################################
  # NT / TLUA = 1, TLUB = 1
  ########################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: d
      TransposeA: False
      TransposeB: True
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - BufferLoad: [True]
        - BufferStore: [True]
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - WorkGroupMapping: [8]
      ForkParameters:
        - VectorWidth: [2]
        - ThreadTile:
          - [ 2, 2 ]
        - WorkGroup:
          - [ 16, 16, 1 ]  # 32x32
        - DepthU: [16,32]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [16777216], [16], [1], [16] ]  # strideA = 16777216, should fail on DU >= 32 (For tensorA-N)
          - Range: [ [16], [16777216], [1], [16] ]  # strideB = 16777216, should fail on DU >= 32 (For tensorB-T)

  ########################################
  # TN / TLUA = 0, TLUB = 0
  ########################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: d
      TransposeA: True
      TransposeB: False
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - BufferLoad: [True]
        - BufferStore: [True]
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - WorkGroupMapping: [8]
      ForkParameters:
        - VectorWidth: [2]
        - ThreadTile:
          - [ 2, 2 ]
        - WorkGroup:
          - [ 8, 8, 1 ]   # 16x16
          - [ 8, 16, 1 ]  # 16x32
          - [ 16, 8, 1 ]  # 32x16
        - DepthU: [16]      # DU doesn't affect bufferload limit in TN
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [16], [16], [1], [16777216] ]  # strideA = 16777216, should fail on MT0 >= 32 (For tensorA-T)  # strideB = 16777216, should fail on MT1 >= 32 (For tensorB-N)

  ########################################
  # TT / TLUA = 0, TLUB = 1
  ########################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: d
      TransposeA: True
      TransposeB: True
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - BufferLoad: [True]
        - BufferStore: [True]
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - WorkGroupMapping: [8]
      ForkParameters:
        - VectorWidth: [2]
        - ThreadTile:
          - [ 2, 2 ]
        - WorkGroup:
          - [ 8, 4, 2 ]   # 16x8
          - [ 16, 4, 1 ]  # 32x8
        - DepthU: [16,32]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [16], [16], [1], [16777216] ]  # strideA = 16777216, should fail on MT0 >= 32 (For tensorA-T)
          - Range: [ [16], [16777216], [1], [16] ]  # strideB = 16777216, should fail on DU >= 32 (For tensorB-T)
