# benchmark assembly and source kernels
GlobalParameters:
  MinimumRequiredVersion: 3.2.0
  CMakeBuildType: Release
  PrintLevel: 1
  ForceRedoBenchmarkProblems: True
  ForceRedoLibraryLogic: True
  ForceRedoLibraryClient: True
  EnqueuesPerSync: 1
  SyncsPerBenchmark: 1
  NumElementsToValidate: 128
  ValidationMaxToPrint: 4
  ValidationPrintValids: False
  ShortNames: False
  MergeFiles: True
  DataInitTypeAB: 3
  DataInitTypeC: 3
  KernelTime: True

BenchmarkProblems:

  - # sgemm NN
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: False
      TransposeB: False
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Assembly
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - LoopTail: [True]
        - EdgeType: ["ShiftPtr"]
        - KernelLanguage: ["Assembly"]
      ForkParameters:
        - PrefetchLocalRead: [False]
        - PrefetchGlobalRead: [False]
        - ThreadTile:
          - [ 4, 8 ]
          - [ 8, 8 ]
        - WorkGroup:
          - [ 16, 16,  1 ]
          - [  8,  8,  1 ]
        - DepthU: [4, 8]
        - VectorWidth: [2, 4]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [1023,1,1025], 0, [2], [127,1,129] ]

    - # BenchmarkProblemSizeGroup - Source
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - LoopTail: [True]
        - EdgeType: ["ShiftPtr"]
        - KernelLanguage: ["Source"]
      ForkParameters:
        - PrefetchLocalRead: [False]
        - PrefetchGlobalRead: [False]
        - ThreadTile:
          - [ 4, 8 ]
          - [ 8, 8 ]
        - WorkGroup:
          - [ 16, 16,  1 ]
          - [  8,  8,  1 ]
        - DepthU: [4, 8]
        - VectorWidth: [1]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [127,1,129], 0, [2], [127,1,129] ]

  - # sgemm NT
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: False
      TransposeB: True
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Assembly
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - LoopTail: [True]
        - EdgeType: ["ShiftPtr"]
        - KernelLanguage: ["Assembly"]
      ForkParameters:
        - PrefetchLocalRead: [False]
        - PrefetchGlobalRead: [False]
        - ThreadTile:
          - [ 4, 8 ]
          - [ 8, 8 ]
        - WorkGroup:
          - [ 16, 16,  1 ]
          - [  8,  8,  1 ]
        - DepthU: [4, 8]
        - VectorWidth: [2, 4]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [1023,1,1025], 0, [2], [127,1,129] ]

    - # BenchmarkProblemSizeGroup - Source
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - LoopTail: [True]
        - EdgeType: ["ShiftPtr"]
        - KernelLanguage: ["Source"]
      ForkParameters:
        - PrefetchLocalRead: [False]
        - PrefetchGlobalRead: [False]
        - ThreadTile:
          - [ 4, 8 ]
          - [ 8, 8 ]
        - WorkGroup:
          - [ 16, 16,  1 ]
          - [  8,  8,  1 ]
        - DepthU: [4, 8]
        - VectorWidth: [1]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [127,1,129], 0, [2], [127,1,129] ]

  - # sgemm TN
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: True
      TransposeB: False
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Assembly
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - LoopTail: [True]
        - EdgeType: ["ShiftPtr"]
        - KernelLanguage: ["Assembly"]
      ForkParameters:
        - PrefetchLocalRead: [False]
        - PrefetchGlobalRead: [False]
        - ThreadTile:
          - [ 4, 8 ]
          - [ 8, 8 ]
        - WorkGroup:
          - [ 16, 16,  1 ]
          - [  8,  8,  1 ]
        - DepthU: [4, 8]
        - VectorWidth: [2, 4]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [1023,1,1025], 0, [2], [127,1,129] ]

    - # BenchmarkProblemSizeGroup - Source
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - LoopTail: [True]
        - EdgeType: ["ShiftPtr"]
        - KernelLanguage: ["Source"]
      ForkParameters:
        - PrefetchLocalRead: [False]
        - PrefetchGlobalRead: [False]
        - ThreadTile:
          - [ 4, 8 ]
          - [ 8, 8 ]
        - WorkGroup:
          - [ 16, 16,  1 ]
          - [  8,  8,  1 ]
        - DepthU: [4, 8]
        - VectorWidth: [1]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [127,1,129], 0, [2], [127,1,129] ]

  - # sgemm TT
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: True
      TransposeB: True
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Assembly
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - LoopTail: [True]
        - EdgeType: ["ShiftPtr"]
        - KernelLanguage: ["Assembly"]
      ForkParameters:
        - PrefetchLocalRead: [False]
        - PrefetchGlobalRead: [False]
        - ThreadTile:
          - [ 4, 8 ]
          - [ 8, 8 ]
        - WorkGroup:
          - [ 16, 16,  1 ]
          - [  8,  8,  1 ]
        - DepthU: [4, 8]
        - VectorWidth: [2, 4]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [1023,1,1025], 0, [2], [127,1,129] ]

    - # BenchmarkProblemSizeGroup - Source
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - LoopTail: [True]
        - EdgeType: ["ShiftPtr"]
        - KernelLanguage: ["Source"]
      ForkParameters:
        - PrefetchLocalRead: [False]
        - PrefetchGlobalRead: [False]
        - ThreadTile:
          - [ 4, 8 ]
          - [ 8, 8 ]
        - WorkGroup:
          - [ 16, 16,  1 ]
          - [  8,  8,  1 ]
        - DepthU: [4, 8]
        - VectorWidth: [1]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [127,1,129], 0, [2], [127,1,129] ]

LibraryLogic:
  SolutionImportanceMin: 0
LibraryClient:
