# benchmark assembly and source kernels
GlobalParameters:
  MinimumRequiredVersion: 4.1.1
  NumElementsToValidate: -1
  KernelTime: True

BenchmarkProblems:
  - # hgemm TN
    - # ProblemType
      OperationType: GEMM
      DataType: h
      TransposeA: True
      TransposeB: False
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Assembly
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - LoopTail: [True]
        - EdgeType: ["ShiftPtr"]
        - KernelLanguage: ["Assembly"]
      ForkParameters:
        - GlobalSplitU: [1, 3]
        - PrefetchLocalRead: [True]
        - PrefetchGlobalRead: [False]
        - ThreadTile:
          - [ 4, 2 ]
          - [ 4, 8 ]
          - [ 8, 8 ]
        - WorkGroup:
          - [ 16, 16,  1 ]
          - [ 32,  4,  1 ]
        - DepthU: [8]
        - VectorWidth: [-1]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [127,1,129], 0, [2], [63,1,65] ]

    - # BenchmarkProblemSizeGroup - Assembly
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - LoopTail: [True]
        - EdgeType: ["ShiftPtr"]
      ForkParameters:
        - KernelLanguage: ["Assembly"]
        - GlobalSplitU: [1, 3]
        - PrefetchLocalRead: [True]
        - PrefetchGlobalRead: [False]
        - ThreadTile:
          - [ 8, 2 ]
          - [ 2, 8 ]
          - [ 16, 2 ]
          - [ 2, 16 ]
        - WorkGroup:
          - [ 16, 16,  1 ]
          - [  8,  8,  1 ]
        - DepthU: [16]
        - VectorWidth: [-1]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [127,1,129], 0, [2], [63,1,65] ]
