BenchmarkProblems:
  ########################################
  # NN - standard
  ########################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: h
      TransposeA: False
      TransposeB: True
      UseBeta: True
      Batched: True
