GlobalParameters:
  MinimumRequiredVersion: 4.14.0
  PrintLevel: 1
  ForceRedoBenchmarkProblems: True
  ForceRedoLibraryLogic: True
  ForceRedoLibraryClient: True
  CMakeBuildType: Release
  EnqueuesPerSync: 1
  SyncsPerBenchmark: 1
  LibraryPrintDebug: False
  NumElementsToValidate: 10000
  ValidationMaxToPrint: 4
  ValidationPrintValids: False
  ShortNames: False
  MergeFiles: True
  Platform: 0
  Device: 0
  KernelTime: True
  PinClocks: False
  SleepPercent: 0
  PrintSolutionRejectionReason: True
  DataInitTypeA: 3
  DataInitTypeB: 3
  #DataInitTypeC: 0
  #DataInitTypeD: 0
  DataInitTypeBeta: 2
  DataInitTypeAlpha: 1
  PrintTensorA: 0
  PrintTensorB: 0
  PrintTensorD: 0
  NewClient: 1

BenchmarkProblems:
  ########################################
  # TN - standard
  ########################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: True
      TransposeB: False
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
      ForkParameters:
        - PrefetchLocalRead: [True]
        - MatrixInstruction:
          - [32, 32, 1, 2]
        - PrefetchGlobalRead: [True]
        - ThreadTile:
          - [ 1, 32 ]
          - [ 2, 32 ]
        - WorkGroup:
          - [ 32, 8, 1 ]
          - [ 64, 4, 1 ]
        - WorkGroupMapping: [1]
        - GlobalSplitU: [1]
        - DepthU: [8]
        - VectorWidth: [4]
        - InnerUnroll: [1, 2]
        - LdsBlockSizePerPad: [128]
        - TransposeLDS: [1]
        - LdsPadA: [0, 2, 4]
        - LdsPadB: [0, 2, 4]
        - SuppressNoLoadLoop: [False, True]
        - OptNoLoadLoop: [0, 1]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Exact: [ 7680, 8192, 1, 8192, 8224, 8224, 8224, 8224 ]
          # - Exact: [ 64, 128, 1, 16 ]
          # - Exact: [ 64, 128, 1, 17 ]
########################################
LibraryLogic:
    ScheduleName: "arcturus"
    DeviceNames: ["Device 7380", "Device 7388", "Device 738c", "Device 7390"]
    ArchitectureName: "gfx908"
