GlobalParameters:
  CMakeBuildType: Release
  DataInitTypeAB: 0
  DataInitTypeBeta: 0
  Device: 0
  EnqueuesPerSync: 1
  ForceRedoBenchmarkProblems: true
  ForceRedoLibraryClient: true
  ForceRedoLibraryLogic: true
  KernelTime: true
  LibraryPrintDebug: false
  MergeFiles: true
  MinimumRequiredVersion: 4.2.0
  NumElementsToValidate: 0
  PinClocks: false
  Platform: 0
  PrintWinnersOnly: 1
  ShortNames: false
  SleepPercent: 50
  SolutionSelectionAlg: 1
  SyncsPerBenchmark: 1
  ValidationMaxToPrint: 4
  ValidationPrintValids: false
BenchmarkProblems:
- - {Batched: true, DataType: s, OperationType: GEMM, TransposeA: true, TransposeB: false,
    UseBeta: true}
  - BenchmarkCommonParameters:
    - LoopTail: [true]
    - KernelLanguage: [Assembly]
    - EdgeType: [ShiftPtr]
    BenchmarkFinalParameters:
    - ProblemSizes:
      - Exact: [768, 16, 1, 768]
    BenchmarkForkParameters: null
    BenchmarkJoinParameters: null
    ForkParameters:
    - PrefetchGlobalRead: [false, true]
    - WorkGroupMapping: [1, 8]
    - DepthU: [8, 16, 32]
    - LdsPadA: [0, -1]
    - PrefetchLocalRead: [false, true]
    - LdsPadB: [0, -1]
    - GlobalSplitU: [1, 8]
    - VectorWidth: [2, 4]
    - GlobalReadVectorWidth: [1, 2, 4]
    - FractionalLoad: [0, 1]
    - ThreadTile:
      - [2, 2]
      - [4, 2]
      - [2, 4]
      - [4, 4]
    - WorkGroup:
      - [16, 16, 1]
      - [8, 16, 2]
      - [16, 8, 2]
      - [4, 16, 4]
      - [16, 4, 4]
    InitialSolutionParameters: null
    JoinParameters: null
  - BenchmarkCommonParameters:
    - LoopTail: [true]
    - KernelLanguage: [Assembly]
    - EdgeType: [ShiftPtr]
    - GlobalSplitU: [1]
    BenchmarkFinalParameters:
    - ProblemSizes:
      - Exact: [30522, 320, 1, 768]
      - Exact: [3072, 4096, 1, 768]
      - Exact: [768, 4096, 1, 3072]
      - Exact: [768, 4096, 1, 768]
      - Exact: [30522, 160, 1, 768]
      - Exact: [30522, 640, 1, 768]
      - Exact: [768, 640, 1, 768]
      - Exact: [30522, 1280, 1, 768]
      - Exact: [768, 1280, 1, 768]
    BenchmarkForkParameters: null
    BenchmarkJoinParameters: null
    ForkParameters:
    - PrefetchGlobalRead: [false, true]
    - WorkGroupMapping: [1, 8]
    - DepthU: [8, 16, 32]
    - PrefetchLocalRead: [false, true]
    - VectorWidth: [2, 4]
    - GlobalReadVectorWidth: [1, 2, 4]
    - FractionalLoad: [0, 1]
    - ThreadTile:
      - [4, 4]
      - [6, 4]
      - [4, 6]
      - [4, 8]
      - [8, 4]
      - [8, 8]
    - WorkGroup:
      - [16, 16, 1]
    InitialSolutionParameters: null
    JoinParameters: null
  - BenchmarkCommonParameters:
    - LoopTail: [true]
    - KernelLanguage: [Assembly]
    - EdgeType: [ShiftPtr]
    BenchmarkFinalParameters:
    - ProblemSizes:
      - Exact: [768, 320, 1, 768]
      - Exact: [768, 32, 1, 768]
      - Exact: [768, 64, 1, 768]
    BenchmarkForkParameters: null
    BenchmarkJoinParameters: null
    ForkParameters:
    - PrefetchGlobalRead: [false, true]
    - WorkGroupMapping: [1, 8]
    - DepthU: [8, 16]
    - PrefetchLocalRead: [false, true]
    - GlobalSplitU: [1, 8]
    - VectorWidth: [2, 4]
    - GlobalReadVectorWidth: [1, 2, 4]
    - FractionalLoad: [0, 1]
    - ThreadTile:
      - [2, 2]
      - [4, 2]
      - [2, 4]
      - [4, 4]
    - WorkGroup:
      - [16, 16, 1]
      - [8, 16, 2]
      - [16, 8, 2]
      - [4, 16, 4]
      - [16, 4, 4]
    InitialSolutionParameters: null
    JoinParameters: null
  - BenchmarkCommonParameters:
    - LoopTail: [true]
    - KernelLanguage: [Assembly]
    - EdgeType: [ShiftPtr]
    BenchmarkFinalParameters:
    - ProblemSizes:
      - Exact: [2, 16, 1, 768]
      - Exact: [2, 8, 1, 768]
      - Exact: [2, 32, 1, 768]
      - Exact: [2, 64, 1, 768]
    BenchmarkForkParameters: null
    BenchmarkJoinParameters: null
    ForkParameters:
    - PrefetchGlobalRead: [false, true]
    - WorkGroupMapping: [1, 8]
    - DepthU: [8, 16, 32]
    - LdsPadA: [0, -1]
    - PrefetchLocalRead: [false, true]
    - LdsPadB: [0, -1]
    - GlobalSplitU: [1, 4]
    - VectorWidth: [2, 4]
    - GlobalReadVectorWidth: [1, 2, 4]
    - FractionalLoad: [0, 1]
    - ThreadTile:
      - [2, 2]
      - [4, 2]
      - [2, 4]
    - WorkGroup:
      - [16, 16, 1]
      - [8, 16, 2]
      - [16, 8, 2]
      - [4, 16, 4]
      - [16, 4, 4]
      - [32, 8, 4]
      - [8, 32, 4]
    InitialSolutionParameters: null
    JoinParameters: null
  - BenchmarkCommonParameters:
    - LoopTail: [true]
    - KernelLanguage: [Assembly]
    - EdgeType: [ShiftPtr]
    - GlobalSplitU: [1]
    BenchmarkFinalParameters:
    - ProblemSizes:
      - Exact: [256, 256, 192, 64]
      - Exact: [256, 256, 96, 64]
      - Exact: [128, 128, 384, 64]
      - Exact: [128, 128, 96, 64]
      - Exact: [64, 64, 768, 64]
      - Exact: [64, 64, 96, 64]
    BenchmarkForkParameters: null
    BenchmarkJoinParameters: null
    ForkParameters:
    - PrefetchGlobalRead: [false, true]
    - WorkGroupMapping: [1, 8]
    - DepthU: [8, 16, 32]
    - LdsPadA: [0, -1]
    - PrefetchLocalRead: [false, true]
    - LdsPadB: [0, -1]
    - VectorWidth: [2, 4]
    - GlobalReadVectorWidth: [1, 2, 4]
    - FractionalLoad: [0, 1]
    - ThreadTile:
      - [4, 4]
      - [4, 2]
      - [2, 4]
      - [4, 8]
      - [8, 4]
      - [8, 8]
    - WorkGroup:
      - [16, 16, 1]
      - [16, 8, 1]
      - [8, 16, 1]
    InitialSolutionParameters: null
    JoinParameters: null
LibraryLogic:
  ArchitectureName: gfx906
  DeviceNames: [Device 66a0, Device 66a1, Device 66a7, Vega 20]
  ScheduleName: vega20
LibraryClient:
