GlobalParameters:
  NewClient: 2
  BestSolution: True
  NetworkName: Transformer
ProblemType:
  OperationType: GEMM
  DataType: s
  TransposeA: False
  TransposeB: False
  UseBeta: True
  Batched: True
  ProblemSizes:
    Train:
    - Exact: [count: 8, size: [1024, 3072, 1, 3072, 1056, 1056, 3136, 3104]]
    Validate:
    - Exact: [count: 8, size: [1024, 3072, 1, 3072, 1056, 1056, 3136, 3104]]
ProblemType2:
  OperationType: GEMM
  DataType: s
  TransposeA: False
  TransposeB: True
  UseBeta: True
  Batched: True
  ProblemSizes:
    Train:
    - Exact: [count: 16, size: [1024, 1024, 1, 3072, 1056, 1056, 1088, 3072]]
    Validate:
    - Exact: [count: 16, size: [1024, 1024, 1, 3072, 1056, 1056, 1088, 3072]]
ProblemType3:
  OperationType: GEMM
  DataType: s
  TransposeA: True
  TransposeB: False
  UseBeta: True
  Batched: True
  ProblemSizes:
    Train:
    - Exact: [count: 11, size: [30528, 2048, 1, 1024, 30554, 30554, 1088, 1056]]
    Validate:
    - Exact: [count: 11, size: [30528, 2048, 1, 1024, 30554, 30554, 1088, 1056]]
#ProblemType4:
#  OperationType: GEMM
#  DataType: h
#  TransposeA: False
#  TransposeB: False
#  UseBeta: True
#  Batched: True
#  ProblemSizes:
#    Train:
#    - Exact: [count: 7, size: !!python/tuple [5518, 5518, 1, 3118]]
#    - Exact: [count: 13, size: !!python/tuple [2768, 2768, 512, 1568]]
#    Validate:
#    - Exact: [count: 8, size: !!python/tuple [2752, 2752, 64, 1552]]
