GlobalParameters:
  BoundsCheck: False
  KernelTime: True
  NewClient: 2
  NumBenchmarks: 30
  DataInitTypeBeta: 0
  DataInitTypeAlpha: 1
  
BenchmarkProblems:

  ########################################
  # NN
  ########################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: d
      TransposeA: False
      TransposeB: False
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - BufferLoad: [True]
        - BufferStore: [True]
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - LoopTail: [True]
        - WorkGroupMapping: [8]
      ForkParameters:
        - VectorWidth: [2]        
        - PrefetchLocalRead: [0,1]
        - PersistentKernel: [0,2,3,4]
        - ThreadTile:
          - [ 8, 4 ]
        - WorkGroup:
          - [ 16, 32, 1 ]
        - DepthU: [8,16]        # DU = 32 cost too much LDS
        - StaggerU: [8,16,32]
        - StaggerUStride: [64,128,256]      
        - StaggerUMapping: [0]
        - InnerUnroll: [1]      # 1 is always best
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Range: [ [1000000], [250], [1], [250] ]

LibraryLogic:
    ScheduleName: "vega20"
    DeviceNames: ["Device 66a0", "Device 66a1", "Device 66a7", "Device 66af", "Vega 20"]
    ArchitectureName: "gfx906"

LibraryClient:
