#!/usr/bin/env python3

from __future__ import print_function

import os
import subprocess
import sys

argv = list(sys.argv)

basepath = '/opt/rocm'
filepath = 'lib/cmake/hcc/hcc-config.cmake'

flags = []

if '-R' in sys.argv:
    flags += ['-R']
    sys.argv.remove('-R')

if len(argv) > 1:
    basepath = argv[1]

if len(sys.argv) > 2:
    print("Usage: {} [-R] [basepath or filepath]".format(sys.argv[0]))
    exit(-1)

if os.path.isfile(basepath):
    filename = basepath
else:
    filename = os.path.join(basepath, filepath)

diff = """
41c41
< add_library(hsa-runtime64 SHARED IMPORTED GLOBAL)
---
> add_library(hsa-runtime64 SHARED IMPORTED)
"""

args = ['patch'] + flags + [filename]

print(' '.join(args))

result = subprocess.run(args, input=diff.encode())
result.check_returncode()

