GlobalParameters:
  MinimumRequiredVersion: 4.14.0
  PrintLevel: 1
  ForceRedoBenchmarkProblems: True
  ForceRedoLibraryLogic: True
  ForceRedoLibraryClient: True
  CMakeBuildType: Release
  EnqueuesPerSync: 1
  SyncsPerBenchmark: 1
  LibraryPrintDebug: False
  NumElementsToValidate: 0
  ValidationMaxToPrint: 4
  ValidationPrintValids: False
  ShortNames: False
  MergeFiles: True
  Platform: 0
  Device: 0
  KernelTime: True
  PinClocks: False
  SleepPercent: 50
  PrintSolutionRejectionReason: False
  DataInitTypeA: 3
  DataInitTypeB: 3
  #DataInitTypeC: 0
  #DataInitTypeD: 0
  #DataInitTypeAB: 0 # Ben's favorite setting
  DataInitTypeBeta: 0
  DataInitTypeAlpha: 1
  PrintTensorA: 0
  PrintTensorB: 0
  PrintTensorD: 0
  SolutionSelectionAlg: 1
  PrintWinnersOnly: 1
  NewClient: 2

BenchmarkProblems:
  ########################################
  # NN - standard
  ########################################
  -
    - # ProblemType
      OperationType: GEMM
      DataType: s
      TransposeA: True
      TransposeB: False
      UseBeta: True
      Batched: True

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - PrefetchGlobalRead: [True]
        - PrefetchLocalRead: [True]
      ForkParameters:
        - MatrixInstruction:
          - [32, 32, 1, 2]
        - ThreadTile:
          - [ 1, 32 ]
          - [ 2, 32 ]
          - [ 4, 32 ]
          - [ 1, 64 ]
          - [ 2, 64 ]
        - WorkGroup:
          - [ 64, 4, 1 ]
          - [ 16, 16, 1 ]
        - FractionalLoad: [0,1] #
        #- WorkGroupMapping: [4,8,16] # [16]
        - DepthU: [8,16,32] # [8]
        - TransposeLDS: [0,1]
        - DirectToLds: [False,True]
        - VectorWidth: [2,4] #
        - GlobalReadVectorWidth: [-1,4]
        #- InnerUnroll: [1,2]
        - ScheduleIterAlg: [1,3]
        #- OptNoLoadLoop: [0,1,2]
        - StoreVectorWidth: [-1,2,4]
        #- DisableVgprOverlapping: [True,False]
        #- WaveSeparateGlobalReadA: [True,False]
        #- WaveSeparateGlobalReadB: [True,False]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Exact: [1024, 3072, 1, 1024]
          - Exact: [1024, 3072, 1, 4096]
          - Exact: [1024, 6, 1, 1024]
          - Exact: [1024, 6, 1, 2]
          - Exact: [4096, 3072, 1, 1024]
          - Exact: [512, 512, 96, 64]

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - PrefetchGlobalRead: [True]
        - PrefetchLocalRead: [True]
      ForkParameters:
        - MatrixInstruction:
          - [32, 32, 2, 1]
        - ThreadTile:
          - [ 1, 32 ] #-
          - [ 1, 64 ] #-
          - [ 2, 32 ] ##
          - [ 4, 32 ] ##
          - [ 4, 64 ] ##
        - WorkGroup:
          - [ 16, 16, 1 ]
        - FractionalLoad: [0,1]
        #- WorkGroupMapping: [4,8,16] # [16]
        - DepthU: [8,16,32] # [8]
        - TransposeLDS: [0,1]
        - DirectToLds: [False,True]
        - VectorWidth: [2,4] #
        - GlobalReadVectorWidth: [-1,4] #
        #- InnerUnroll: [1,2]
        - ScheduleIterAlg: [1,3]
        #- OptNoLoadLoop: [0,1,2]
        - StoreVectorWidth: [-1,2,4]
        #- DisableVgprOverlapping: [True,False]
        #- WaveSeparateGlobalReadA: [True,False]
        #- WaveSeparateGlobalReadB: [True,False]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Exact: [1024, 3072, 1, 1024]
          - Exact: [1024, 3072, 1, 4096]
          - Exact: [1024, 6, 1, 1024]
          - Exact: [1024, 6, 1, 2]
          - Exact: [4096, 3072, 1, 1024]
          - Exact: [512, 512, 96, 64]

    - # BenchmarkProblemSizeGroup - Standard+
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - PrefetchGlobalRead: [True]
        - PrefetchLocalRead: [True]
      ForkParameters:
        - MatrixInstruction:
          - [32, 32, 2, 1]
        - ThreadTile:
          - [ 1, 64 ]
          - [ 1, 128 ]
        - WorkGroup:
          - [ 64, 4, 1 ]
        - FractionalLoad: [0,1]
        #- WorkGroupMapping: [4,8,16] # [16]
        - DepthU: [8,16,32] # [8]
        - TransposeLDS: [0,1]
        - DirectToLds: [False,True]
        - VectorWidth: [2,4] #
        - GlobalReadVectorWidth: [-1,4] #
        #- InnerUnroll: [1,2]
        - ScheduleIterAlg: [1,3]
        #- OptNoLoadLoop: [0,1,2]
        - StoreVectorWidth: [-1,2,4]
        #- DisableVgprOverlapping: [True,False]
        #- WaveSeparateGlobalReadA: [True,False]
        #- WaveSeparateGlobalReadB: [True,False]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Exact: [1024, 3072, 1, 1024]
          - Exact: [1024, 3072, 1, 4096]
          - Exact: [1024, 6, 1, 1024]
          - Exact: [1024, 6, 1, 2]
          - Exact: [4096, 3072, 1, 1024]
          - Exact: [512, 512, 96, 64]

    - # BenchmarkProblemSizeGroup - Standard+
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - PrefetchGlobalRead: [True]
        - PrefetchLocalRead: [True]
      ForkParameters:
        - MatrixInstruction:
          - [32, 32, 2, 1]
        - ThreadTile:
          - [ 1, 32 ]
          - [ 2, 32 ]
          - [ 2, 64 ]
        - WorkGroup:
          - [ 32, 8, 1 ]
        - FractionalLoad: [0,1]
        #- WorkGroupMapping: [4,8,16] # [16]
        - DepthU: [8,16,32] # [8]
        - TransposeLDS: [0,1]
        - DirectToLds: [False,True]
        - VectorWidth: [2,4] #
        - GlobalReadVectorWidth: [-1,4] #
        #- InnerUnroll: [1,2]
        - ScheduleIterAlg: [1,3]
        #- OptNoLoadLoop: [0,1,2]
        - StoreVectorWidth: [-1,2,4]
        #- DisableVgprOverlapping: [True,False]
        #- WaveSeparateGlobalReadA: [True,False]
        #- WaveSeparateGlobalReadB: [True,False]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Exact: [1024, 3072, 1, 1024]
          - Exact: [1024, 3072, 1, 4096]
          - Exact: [1024, 6, 1, 1024]
          - Exact: [1024, 6, 1, 2]
          - Exact: [4096, 3072, 1, 1024]
          - Exact: [512, 512, 96, 64]

    - # BenchmarkProblemSizeGroup - Standard
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - PrefetchGlobalRead: [True]
        - PrefetchLocalRead: [True]
      ForkParameters:
        - MatrixInstruction:
          - [16, 16, 1, 4]
        - ThreadTile:
          - [ 1, 16 ] ##
          - [ 2, 16 ]
          - [ 4, 16 ]
          - [ 8, 16 ]
          - [ 1, 32 ] ##
          - [ 2, 32 ]
          - [ 4, 32 ]
        - WorkGroup:
          - [ 16, 16, 1 ]
          - [ 64, 4, 1 ]
        - FractionalLoad: [0,1]
        #- WorkGroupMapping: [4,8,16] # [16]
        - DepthU: [8,16,32] # [8]
        - TransposeLDS: [0,1]
        - DirectToLds: [False,True]
        - VectorWidth: [2,4]
        - GlobalReadVectorWidth: [-1,4]
        #- InnerUnroll: [1,2]
        - ScheduleIterAlg: [1,3]
        #- OptNoLoadLoop: [0,1,2]
        - StoreVectorWidth: [-1,2,4]
        #- DisableVgprOverlapping: [True,False]
        #- WaveSeparateGlobalReadA: [True,False]
        #- WaveSeparateGlobalReadB: [True,False]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Exact: [1024, 3072, 1, 1024]
          - Exact: [1024, 3072, 1, 4096]
          - Exact: [1024, 6, 1, 1024]
          - Exact: [1024, 6, 1, 2]
          - Exact: [4096, 3072, 1, 1024]
          - Exact: [512, 512, 96, 64]

    - # BenchmarkProblemSizeGroup - Standard+
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - PrefetchGlobalRead: [True]
        - PrefetchLocalRead: [True]
      ForkParameters:
        - MatrixInstruction:
          - [16, 16, 1, 4]
        - ThreadTile:
          - [ 2, 16 ]
          - [ 4, 16 ]
          - [ 2, 32 ]
          - [ 4, 32 ]
        - WorkGroup:
          - [ 32, 8, 1 ]
        - FractionalLoad: [0,1]
        #- WorkGroupMapping: [4,8,16] # [16]
        - DepthU: [8,16,32] # [8]
        - TransposeLDS: [0,1]
        - DirectToLds: [False,True]
        - VectorWidth: [2,4]
        - GlobalReadVectorWidth: [-1,4]
        #- InnerUnroll: [1,2]
        - ScheduleIterAlg: [1,3]
        #- OptNoLoadLoop: [0,1,2]
        - StoreVectorWidth: [-1,2,4]
        #- DisableVgprOverlapping: [True,False]
        #- WaveSeparateGlobalReadA: [True,False]
        #- WaveSeparateGlobalReadB: [True,False]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Exact: [1024, 3072, 1, 1024]
          - Exact: [1024, 3072, 1, 4096]
          - Exact: [1024, 6, 1, 1024]
          - Exact: [1024, 6, 1, 2]
          - Exact: [4096, 3072, 1, 1024]
          - Exact: [512, 512, 96, 64]

    - # BenchmarkProblemSizeGroup - Standard+
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - PrefetchGlobalRead: [True]
        - PrefetchLocalRead: [True]
      ForkParameters:
        - MatrixInstruction:
          - [16, 16, 4, 1]
        - ThreadTile:
          - [ 4, 16 ]
          - [ 4, 32 ]
          - [ 8, 32 ]
          - [ 8, 32 ]
        - WorkGroup:
          - [ 16, 16, 1 ]
        - FractionalLoad: [0,1]
        #- WorkGroupMapping: [4,8,16] # [16]
        - DepthU: [8,16,32] # [8]
        - TransposeLDS: [0,1]
        - DirectToLds: [False,True]
        - VectorWidth: [2,4]
        - GlobalReadVectorWidth: [-1,4]
        #- InnerUnroll: [1,2]
        - ScheduleIterAlg: [1,3]
        #- OptNoLoadLoop: [0,1,2]
        - StoreVectorWidth: [-1,2,4]
        #- DisableVgprOverlapping: [True,False]
        #- WaveSeparateGlobalReadA: [True,False]
        #- WaveSeparateGlobalReadB: [True,False]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Exact: [1024, 3072, 1, 1024]
          - Exact: [1024, 3072, 1, 4096]
          - Exact: [1024, 6, 1, 1024]
          - Exact: [1024, 6, 1, 2]
          - Exact: [4096, 3072, 1, 1024]
          - Exact: [512, 512, 96, 64]

    - # BenchmarkProblemSizeGroup - Standard+
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - PrefetchGlobalRead: [True]
        - PrefetchLocalRead: [True]
      ForkParameters:
        - MatrixInstruction:
          - [16, 16, 4, 1]
        - ThreadTile:
          - [ 2, 32 ]
          - [ 2, 64 ]
          - [ 4, 32 ]
          - [ 4, 64 ]
        - WorkGroup:
          - [ 32, 8, 1 ]
        - FractionalLoad: [0,1]
        #- WorkGroupMapping: [4,8,16] # [16]
        - DepthU: [8,16,32] # [8]
        - TransposeLDS: [0,1]
        - DirectToLds: [False,True]
        - VectorWidth: [2,4]
        - GlobalReadVectorWidth: [-1,4]
        #- InnerUnroll: [1,2]
        - ScheduleIterAlg: [1,3]
        #- OptNoLoadLoop: [0,1,2]
        - StoreVectorWidth: [-1,2,4]
        #- DisableVgprOverlapping: [True,False]
        #- WaveSeparateGlobalReadA: [True,False]
        #- WaveSeparateGlobalReadB: [True,False]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Exact: [1024, 3072, 1, 1024]
          - Exact: [1024, 3072, 1, 4096]
          - Exact: [1024, 6, 1, 1024]
          - Exact: [1024, 6, 1, 2]
          - Exact: [4096, 3072, 1, 1024]
          - Exact: [512, 512, 96, 64]

    - # BenchmarkProblemSizeGroup - Standard+
      InitialSolutionParameters:
      BenchmarkCommonParameters:
        - KernelLanguage: ["Assembly"]
        - EdgeType: ["ShiftPtr"]
        - PrefetchGlobalRead: [True]
        - PrefetchLocalRead: [True]
      ForkParameters:
        - MatrixInstruction:
          - [16, 16, 4, 1]
        - ThreadTile:
          - [ 1, 64 ]
          - [ 2, 64 ]
          - [ 2, 128 ]
        - WorkGroup:
          - [ 64, 4, 1 ]
        - FractionalLoad: [0,1]
        #- WorkGroupMapping: [4,8,16] # [16]
        - DepthU: [8,16,32] # [8]
        - TransposeLDS: [0,1]
        - DirectToLds: [False,True]
        - VectorWidth: [2,4]
        - GlobalReadVectorWidth: [-1,4]
        #- InnerUnroll: [1,2]
        - ScheduleIterAlg: [1,3]
        #- OptNoLoadLoop: [0,1,2]
        - StoreVectorWidth: [-1,2,4]
        #- DisableVgprOverlapping: [True,False]
        #- WaveSeparateGlobalReadA: [True,False]
        #- WaveSeparateGlobalReadB: [True,False]
      BenchmarkForkParameters:
      JoinParameters:
      BenchmarkJoinParameters:
      BenchmarkFinalParameters:
        - ProblemSizes:
          - Exact: [1024, 3072, 1, 1024]
          - Exact: [1024, 3072, 1, 4096]
          - Exact: [1024, 6, 1, 1024]
          - Exact: [1024, 6, 1, 2]
          - Exact: [4096, 3072, 1, 1024]
          - Exact: [512, 512, 96, 64]

########################################
LibraryLogic:
    ScheduleName: "arcturus"
    DeviceNames: ["Device 7380", "Device 7388", "Device 738c", "Device 7390"]
    ArchitectureName: "gfx908"
