- {MinimumRequiredVersion: 4.19.0}
- arcturus
- gfx908
- [Device 7380, Device 7388, Device 738c, Device 7390, Device 731f]
- AllowNoFreeDims: false
  AssignedDerivedParameters: true
  Batched: true
  ComplexConjugateA: false
  ComplexConjugateB: false
  ComputeDataType: 0
  ConvolutionConfig: []
  DataType: 0
  DestDataType: 0
  HighPrecisionAccumulate: false
  Index0: 0
  Index01A: 0
  Index01B: 1
  Index1: 1
  IndexAssignmentsA: [3, 0, 2]
  IndexAssignmentsB: [3, 1, 2]
  IndexAssignmentsLD: [4, 5, 6, 7]
  IndexUnroll: 3
  IndexUnrollA: 0
  IndexUnrollB: 0
  IndicesBatch: [2]
  IndicesFree: [0, 1]
  IndicesSummation: [3]
  NumIndicesBatch: 1
  NumIndicesC: 3
  NumIndicesFree: 2
  NumIndicesLD: 4
  NumIndicesSummation: 1
  OperationType: GEMM
  SetConstStrideA: []
  SetConstStrideB: []
  SilentHighPrecisionAccumulate: false
  TLUA: false
  TLUB: false
  Tensor0: 0
  Tensor1: 1
  TileA: 0
  TileAwareSelection: false
  TileB: 1
  TotalIndices: 4
  TransposeA: true
  TransposeB: false
  UseBeta: true
  UseInitialStridesAB: false
  UseInitialStridesCD: false
  ZeroPadA: []
  ZeroPadB: []
- - AggressivePerfMode: 1
    AssertFree0ElementMultiple: 8
    AssertFree1ElementMultiple: 1
    AssertMinApproxSize: 3
    AssertSizeEqual: {}
    AssertStrideAEqual: {0: 1}
    AssertStrideBEqual: {0: 1}
    AssertStrideCEqual: {0: 1}
    AssertStrideDEqual: {0: 1}
    AssertSummationElementMultiple: 8
    AssignedDerivedParameters: false
    AssignedProblemIndependentDerivedParameters: true
    BufferLoad: true
    BufferStore: true
    CheckDimOverflow: 0
    CheckTensorDimAsserts: false
    DepthU: 32
    DirectToLds: false
    DirectToLdsA: false
    DirectToLdsB: false
    DisableAtomicFail: 0
    DisableKernelPieces: 0
    EdgeType: ShiftPtr
    ExpandPointerSwap: true
    FractionalLoad: 0
    GlobalLoadVectorWidthA: 4
    GlobalLoadVectorWidthB: 4
    GlobalRead2A: true
    GlobalRead2B: true
    GlobalReadCoalesceGroupA: true
    GlobalReadCoalesceGroupB: true
    GlobalReadCoalesceVectorA: true
    GlobalReadCoalesceVectorB: true
    GlobalReadVectorWidth: 4
    GlobalSplitU: 1
    GlobalSplitUSummationAssignmentRoundRobin: true
    GlobalSplitUWorkGroupMappingRoundRobin: false
    GlobalWriteVectorWidth: 4
    GuaranteeNoPartialA: true
    GuaranteeNoPartialB: true
    ISA: [9, 0, 8]
    InnerUnroll: 1
    InterleaveAlpha: 0
    KernelLanguage: Assembly
    LSCA: 32
    LSCB: 32
    LSPA: 64
    LSPB: 64
    LVCA: 8
    LVCB: 8
    LVPA: 16
    LVPB: 16
    LdcEqualsLdd: true
    LdsBlockSizePerPad: -1
    LdsNumElements: 14336
    LdsNumElementsAlignedA: 2048
    LdsNumElementsAlignedB: 4096
    LdsOffsetA: 0
    LdsOffsetA_Blk: 8192
    LdsOffsetB: 2048
    LdsOffsetB_Blk: 10240
    LdsPadA: 0
    LdsPadB: 0
    LocalDotLayout: 1
    LocalRead2A: true
    LocalRead2B: true
    LocalReadVectorWidth: -1
    LocalSplitU: 1
    LocalWrite2A: true
    LocalWrite2B: true
    LocalWriteUseSgprA: false
    LocalWriteUseSgprB: false
    LoopDoWhile: false
    LoopIters: 32
    LoopTail: true
    LoopUnroll: 32
    MacroTile0: 64
    MacroTile1: 128
    MacroTileA: 64
    MacroTileB: 128
    MacroTileShapeMax: 64
    MacroTileShapeMin: 1
    MagicDivAlg: 1
    MatrixInstruction: []
    MaxOccupancy: 40
    MaxVgprNumber: 256
    MinVgprNumber: 0
    NonTemporalA: 0
    NonTemporalB: 0
    NonTemporalC: 0
    NumElementsPerThread: 16
    NumGlobalWriteVectorsPerThread: 4
    NumLoadsA: 1
    NumLoadsB: 2
    NumLoadsCoalescedA: 1
    NumLoadsCoalescedB: 1
    NumLoadsPerpendicularA: 1
    NumLoadsPerpendicularB: 2
    NumThreads: 512
    OptNoLoadLoop: 1
    PackBatchDims: 0
    PackFreeDims: 1
    PackGranularity: 2
    PackSummationDims: 0
    PackedC0IdxChars: [I]
    PackedC0IndicesX: [0]
    PackedC1IdxChars: [J]
    PackedC1IndicesX: [1]
    PerformanceSyncLocation: -1
    PerformanceWaitCount: -1
    PerformanceWaitLocation: -1
    PersistentKernel: 0
    PrefetchAcrossPersistent: 0
    PrefetchGlobalRead: true
    PrefetchLocalRead: true
    ProblemType:
      AllowNoFreeDims: false
      AssignedDerivedParameters: true
      Batched: true
      ComplexConjugateA: false
      ComplexConjugateB: false
      ComputeDataType: 0
      ConvolutionConfig: []
      DataType: 0
      DestDataType: 0
      HighPrecisionAccumulate: false
      Index0: 0
      Index01A: 0
      Index01B: 1
      Index1: 1
      IndexAssignmentsA: [3, 0, 2]
      IndexAssignmentsB: [3, 1, 2]
      IndexAssignmentsLD: [4, 5, 6, 7]
      IndexUnroll: 3
      IndexUnrollA: 0
      IndexUnrollB: 0
      IndicesBatch: [2]
      IndicesFree: [0, 1]
      IndicesSummation: [3]
      NumIndicesBatch: 1
      NumIndicesC: 3
      NumIndicesFree: 2
      NumIndicesLD: 4
      NumIndicesSummation: 1
      OperationType: GEMM
      SetConstStrideA: []
      SetConstStrideB: []
      SilentHighPrecisionAccumulate: false
      TLUA: false
      TLUB: false
      Tensor0: 0
      Tensor1: 1
      TileA: 0
      TileAwareSelection: false
      TileB: 1
      TotalIndices: 4
      TransposeA: true
      TransposeB: false
      UseBeta: true
      UseInitialStridesAB: false
      UseInitialStridesCD: false
      ZeroPadA: []
      ZeroPadB: []
    ReplacementKernel: true
    ScheduleGlobalRead: 1
    ScheduleIterAlg: 1
    ScheduleLocalWrite: 1
    StaggerU: 32
    StaggerUMapping: 0
    StaggerUStride: 256
    StoreVectorWidth: 4
    SubGroup0: 16
    SubGroup1: 32
    SubGroupA: 16
    SubGroupB: 32
    SuppressNoLoadLoop: false
    ThreadTile: [4, 4]
    ThreadTile0: 4
    ThreadTile1: 4
    ThreadTileA: 4
    ThreadTileB: 4
    TransposeLDS: 0
    UnrollIncIsDepthU: 0
    UnrollMemFence: false
    Use64bShadowLimit: 1
    UseInstOffsetForGRO: 0
    UseSgprForGRO: -1
    Valid: true
    VectorAtomicWidth: 1
    VectorStore: -1
    VectorWidth: 4
    WorkGroup: [16, 32, 1]
    WorkGroupMapping: 8
    WorkGroupMappingType: B
    _UseSgprForGRO: 1
    _VectorStore: 1
    _staggerStrideShift: 1
- [2, 3, 0, 1]
- - - [768, 1280, 1, 768, 768, 768, 800, 832]
    - [0, 28306.0]
  - - [3072, 512, 1, 1024, 3072, 3072, 1024, 1024]
    - [0, 25053.2]
  - - [1024, 3072, 1, 1024, 1088, 1088, 1056, 1088]
    - [0, 25791.4]
  - - [1024, 2048, 1, 4096, 1088, 1088, 4128, 4160]
    - [0, 25925.9]
- null
