# This Dockerfile provides a starting point for a ROCm installation of Tensile.

# Parameters related to building hip
ARG base_image

FROM ${base_image}
LABEL maintainer="tensile-maintainer@amd.com"

USER root
ARG user_uid

# Install dependent packages
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    cmake \
    ca-certificates \
    doxygen \
    git \
    graphviz \
    pkg-config \
    python3 \
    python3-dev \
    python3-pip \
    python3-pytest \
    python3-setuptools \
    python3-yaml \
    libnuma1 \
    llvm-6.0-dev \
    libboost-all-dev \
    zlib1g-dev \
    libomp-dev \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# The version of MessagePack supplied in Ubuntu 16.04 is old and won't work
# We need to add a repository that has a suitable version of MessagePack and download from there
RUN echo "deb http://ftp.debian.org/debian stable main" >> /etc/apt/sources.list && \
    apt-get update && apt-get install -y --no-install-recommends libmsgpack-dev libmsgpackc2

RUN pip3 install setuptools --upgrade && \
    pip3 install wheel && \
    pip3 install tox pyyaml msgpack

# Patch hcc-config.cmake in /opt/rocm
#ADD docker/scripts/fix_hcc_config /tmp
#RUN /tmp/fix_hcc_config && rm /tmp/fix_hcc_config

# docker pipeline runs containers with particular uid
# create a jenkins user with this specific uid so it can use sudo privileges
# Grant any member of sudo group password-less sudo privileges
RUN useradd --create-home -u ${user_uid} -o -G sudo --shell /bin/bash jenkins && \
    mkdir -p /etc/sudoers.d/ && \
    echo '%sudo   ALL=(ALL) NOPASSWD:ALL' | tee /etc/sudoers.d/sudo-nopasswd
