# This Dockerfile provides a starting point for a ROCm installation of hipCaffe.

# Parameters related to building hip
ARG base_image

FROM ${base_image}
LABEL maintainer="kent.knox@amd"

USER root
ARG user_uid

# Install dependent packages
# Dependencies:
# * hcc-config.cmake: pkg-config
# * tensile: python2.7, python-pip
# * rocblas-test: gfortran, googletest
# * rocblas-bench: libboost-program-options-dev
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    cmake \
    ca-certificates \
    git \
    pkg-config \
    python2.7 \
    python2.7-dev \
    python-pip \
    python-pytest \
    python-setuptools \
    python-yaml \
    libnuma1 \
    llvm-6.0-dev \
    libboost-all-dev \
    zlib1g-dev \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip install tox pyyaml

# docker pipeline runs containers with particular uid
# create a jenkins user with this specific uid so it can use sudo priviledges
# Grant any member of sudo group password-less sudo privileges
#RUN useradd --create-home -u ${user_uid} -o -G sudo --shell /bin/bash jenkins && \
#    mkdir -p /etc/sudoers.d/ && \
#    echo '%sudo   ALL=(ALL) NOPASSWD:ALL' | tee /etc/sudoers.d/sudo-nopasswd
