#!/usr/bin/env python
from __future__ import print_function
import os
import subprocess
import sys

image = "tensile-static"
command = []
user_args = ['-e', '_USER='+os.environ['USER'], '-e', '_UID='+str(os.getuid())]
volume_args=['-v', os.getcwd()+":/data"]
interactive_args=['-ti']

if len(sys.argv) > 1:
    image = sys.argv[1]

if len(sys.argv) > 2:
    interactive_args = []
    if sys.argv[2] == 'bash':
        command = sys.argv[2:]
    else:
        command = ['bash' '--login', '-c', ' '.join(sys.argv[2:])]

out_args = ['docker', 'run'] + user_args + volume_args + interactive_args + [image] + command
print(' '.join(out_args))
subprocess.check_call(out_args)

