#!/usr/bin/env python

################################################################################
#
# Copyright (C) 2019-2022 Advanced Micro Devices, Inc. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
################################################################################

from __future__ import print_function
import os
import subprocess
import sys

image = "tensile-static"
command = []
user_args = ['-e', '_USER='+os.environ['USER'], '-e', '_UID='+str(os.getuid())]
volume_args=['-v', os.getcwd()+":/data"]
interactive_args=['-ti']

if len(sys.argv) > 1:
    image = sys.argv[1]

if len(sys.argv) > 2:
    interactive_args = []
    if sys.argv[2] == 'bash':
        command = sys.argv[2:]
    else:
        command = ['bash' '--login', '-c', ' '.join(sys.argv[2:])]

out_args = ['docker', 'run'] + user_args + volume_args + interactive_args + [image] + command
print(' '.join(out_args))
subprocess.check_call(out_args)
