- {MinimumRequiredVersion: 4.2.0}
- vega10
- gfx900
- [Device 6863, Device 6862, Device 687f, Device 6860, Device 6861, Device 6864]
- AssignedDerivedParameters: true
  Batched: true
  ComplexConjugateA: false
  ComplexConjugateB: false
  DataType: 4
  HighPrecisionAccumulate: false
  Index0: 0
  Index01A: 0
  Index01B: 1
  Index1: 1
  IndexAssignmentsA: [0, 3, 2]
  IndexAssignmentsB: [1, 3, 2]
  IndexUnroll: 3
  IndexUnrollA: 1
  IndexUnrollB: 1
  IndicesBatch: [2]
  IndicesFree: [0, 1]
  IndicesSummation: [3]
  NumIndicesBatch: 1
  NumIndicesC: 3
  NumIndicesFree: 2
  NumIndicesSummation: 1
  OperationType: GEMM
  SilentHighPrecisionAccumulate: false
  TLUA: true
  TLUB: true
  Tensor0: 0
  Tensor1: 1
  TileA: 0
  TileB: 1
  TotalIndices: 4
  TransposeA: false
  TransposeB: true
  UseBeta: true
  UseInitialStrides: false
- - AssertSummationElementMultiple: 1
    AssignedDerivedParameters: true
    AssignedProblemIndependentDerivedParameters: true
    BufferLoad: true
    BufferStore: true
    DepthU: 16
    DirectToLds: false
    DirectToLdsA: false
    DirectToLdsB: false
    DisableKernelPieces: 0
    EdgeType: ShiftPtr
    FractionalLoad: 0
    GlobalLoadVectorWidthA: 8
    GlobalLoadVectorWidthB: 8
    GlobalRead2A: true
    GlobalRead2B: true
    GlobalReadCoalesceGroupA: true
    GlobalReadCoalesceGroupB: true
    GlobalReadCoalesceVectorA: true
    GlobalReadCoalesceVectorB: true
    GlobalReadVectorWidth: 8
    GlobalSplitU: 1
    GlobalSplitUSummationAssignmentRoundRobin: true
    GlobalSplitUWorkGroupMappingRoundRobin: false
    GlobalWriteVectorWidth: 8
    InnerUnroll: 1
    KernelLanguage: Assembly
    LSCA: 256
    LSCB: 128
    LSPA: 8
    LSPB: 16
    LVCA: 32
    LVCB: 16
    LVPA: 1
    LVPB: 2
    LdsNumElements: 14336
    LdsNumElementsAlignedA: 4096
    LdsNumElementsAlignedB: 2048
    LdsOffsetA: 0
    LdsOffsetA_Blk: 8192
    LdsOffsetB: 4096
    LdsOffsetB_Blk: 12288
    LdsPadA: 0
    LdsPadB: 0
    LocalRead2A: true
    LocalRead2B: true
    LocalSplitU: 1
    LocalWrite2A: true
    LocalWrite2B: true
    LocalWriteUseSgprA: false
    LocalWriteUseSgprB: false
    LoopDoWhile: false
    LoopTail: true
    LoopUnroll: 16
    MacroTile0: 256
    MacroTile1: 128
    MacroTileA: 256
    MacroTileB: 128
    MacroTileShapeMax: 64
    MacroTileShapeMin: 1
    MaxOccupancy: 40
    MinGlobalWriteVectorWidth: 2
    NonTemporalA: 0
    NonTemporalB: 0
    NonTemporalC: 0
    NumElementsPerThread: 128
    NumGlobalWriteVectorsPerThread: 16
    NumLoadsA: 2
    NumLoadsB: 1
    NumLoadsCoalescedA: 1
    NumLoadsCoalescedB: 1
    NumLoadsPerpendicularA: 2
    NumLoadsPerpendicularB: 1
    NumThreads: 256
    PerformanceSyncLocation: -1
    PerformanceWaitCount: -1
    PerformanceWaitLocation: -1
    PersistentKernel: 0
    PreciseBoundsCheck: false
    PrefetchGlobalRead: true
    PrefetchLocalRead: true
    ProblemType:
      AssignedDerivedParameters: true
      Batched: true
      ComplexConjugateA: false
      ComplexConjugateB: false
      DataType: 4
      HighPrecisionAccumulate: false
      Index0: 0
      Index01A: 0
      Index01B: 1
      Index1: 1
      IndexAssignmentsA: [0, 3, 2]
      IndexAssignmentsB: [1, 3, 2]
      IndexUnroll: 3
      IndexUnrollA: 1
      IndexUnrollB: 1
      IndicesBatch: [2]
      IndicesFree: [0, 1]
      IndicesSummation: [3]
      NumIndicesBatch: 1
      NumIndicesC: 3
      NumIndicesFree: 2
      NumIndicesSummation: 1
      OperationType: GEMM
      SilentHighPrecisionAccumulate: false
      TLUA: true
      TLUB: true
      Tensor0: 0
      Tensor1: 1
      TileA: 0
      TileB: 1
      TotalIndices: 4
      TransposeA: false
      TransposeB: true
      UseBeta: true
      UseInitialStrides: false
    SolutionIndex: 0
    SolutionNameMin: Cijk_Ailk_Bjlk_HB_MT256x128x16_GRVW08_PGR1_PLR1_TT16_08_VW08_WG16_16_01_WGM01
    SubGroup0: 16
    SubGroup1: 16
    SubGroupA: 16
    SubGroupB: 16
    ThreadTile: [16, 8]
    ThreadTile0: 16
    ThreadTile1: 8
    ThreadTileA: 16
    ThreadTileB: 8
    UnrollMemFence: false
    UseSgprForGRO: 0
    Valid: true
    VectorStore: true
    VectorWidth: 8
    WorkGroup: [16, 16, 1]
    WorkGroupMapping: 1
    WorkGroupMappingType: B
  - AssertSummationElementMultiple: 1
    AssignedDerivedParameters: true
    AssignedProblemIndependentDerivedParameters: true
    BufferLoad: true
    BufferStore: true
    DepthU: 16
    DirectToLds: false
    DirectToLdsA: false
    DirectToLdsB: false
    DisableKernelPieces: 0
    EdgeType: ShiftPtr
    FractionalLoad: 0
    GlobalLoadVectorWidthA: 8
    GlobalLoadVectorWidthB: 8
    GlobalRead2A: true
    GlobalRead2B: true
    GlobalReadCoalesceGroupA: true
    GlobalReadCoalesceGroupB: true
    GlobalReadCoalesceVectorA: true
    GlobalReadCoalesceVectorB: true
    GlobalReadVectorWidth: 8
    GlobalSplitU: 1
    GlobalSplitUSummationAssignmentRoundRobin: true
    GlobalSplitUWorkGroupMappingRoundRobin: false
    GlobalWriteVectorWidth: 8
    InnerUnroll: 1
    KernelLanguage: Assembly
    LSCA: 256
    LSCB: 128
    LSPA: 8
    LSPB: 16
    LVCA: 32
    LVCB: 16
    LVPA: 1
    LVPB: 2
    LdsNumElements: 14336
    LdsNumElementsAlignedA: 4096
    LdsNumElementsAlignedB: 2048
    LdsOffsetA: 0
    LdsOffsetA_Blk: 8192
    LdsOffsetB: 4096
    LdsOffsetB_Blk: 12288
    LdsPadA: 0
    LdsPadB: 0
    LocalRead2A: true
    LocalRead2B: true
    LocalSplitU: 1
    LocalWrite2A: true
    LocalWrite2B: true
    LocalWriteUseSgprA: false
    LocalWriteUseSgprB: false
    LoopDoWhile: false
    LoopTail: true
    LoopUnroll: 16
    MacroTile0: 256
    MacroTile1: 128
    MacroTileA: 256
    MacroTileB: 128
    MacroTileShapeMax: 64
    MacroTileShapeMin: 1
    MaxOccupancy: 40
    MinGlobalWriteVectorWidth: 2
    NonTemporalA: 0
    NonTemporalB: 0
    NonTemporalC: 0
    NumElementsPerThread: 128
    NumGlobalWriteVectorsPerThread: 16
    NumLoadsA: 2
    NumLoadsB: 1
    NumLoadsCoalescedA: 1
    NumLoadsCoalescedB: 1
    NumLoadsPerpendicularA: 2
    NumLoadsPerpendicularB: 1
    NumThreads: 256
    PerformanceSyncLocation: -1
    PerformanceWaitCount: -1
    PerformanceWaitLocation: -1
    PersistentKernel: 0
    PreciseBoundsCheck: false
    PrefetchGlobalRead: true
    PrefetchLocalRead: true
    ProblemType:
      AssignedDerivedParameters: true
      Batched: true
      ComplexConjugateA: false
      ComplexConjugateB: false
      DataType: 4
      HighPrecisionAccumulate: false
      Index0: 0
      Index01A: 0
      Index01B: 1
      Index1: 1
      IndexAssignmentsA: [0, 3, 2]
      IndexAssignmentsB: [1, 3, 2]
      IndexUnroll: 3
      IndexUnrollA: 1
      IndexUnrollB: 1
      IndicesBatch: [2]
      IndicesFree: [0, 1]
      IndicesSummation: [3]
      NumIndicesBatch: 1
      NumIndicesC: 3
      NumIndicesFree: 2
      NumIndicesSummation: 1
      OperationType: GEMM
      SilentHighPrecisionAccumulate: false
      TLUA: true
      TLUB: true
      Tensor0: 0
      Tensor1: 1
      TileA: 0
      TileB: 1
      TotalIndices: 4
      TransposeA: false
      TransposeB: true
      UseBeta: true
      UseInitialStrides: false
    SolutionIndex: 1
    SolutionNameMin: Cijk_Ailk_Bjlk_HB_MT256x128x16_GRVW08_PGR1_PLR1_TT16_08_VW08_WG16_16_01_WGM08
    SubGroup0: 16
    SubGroup1: 16
    SubGroupA: 16
    SubGroupB: 16
    ThreadTile: [16, 8]
    ThreadTile0: 16
    ThreadTile1: 8
    ThreadTileA: 16
    ThreadTileB: 8
    UnrollMemFence: false
    UseSgprForGRO: 0
    Valid: true
    VectorStore: true
    VectorWidth: 8
    WorkGroup: [16, 16, 1]
    WorkGroupMapping: 8
    WorkGroupMappingType: B
  - AssertSummationElementMultiple: 1
    AssignedDerivedParameters: true
    AssignedProblemIndependentDerivedParameters: true
    BufferLoad: true
    BufferStore: true
    DepthU: 8
    DirectToLds: false
    DirectToLdsA: false
    DirectToLdsB: false
    DisableKernelPieces: 0
    EdgeType: ShiftPtr
    FractionalLoad: 1
    GlobalLoadVectorWidthA: 4
    GlobalLoadVectorWidthB: 2
    GlobalRead2A: true
    GlobalRead2B: true
    GlobalReadCoalesceGroupA: true
    GlobalReadCoalesceGroupB: true
    GlobalReadCoalesceVectorA: true
    GlobalReadCoalesceVectorB: true
    GlobalReadVectorWidth: 8
    GlobalSplitU: 1
    GlobalSplitUSummationAssignmentRoundRobin: true
    GlobalSplitUWorkGroupMappingRoundRobin: false
    GlobalWriteVectorWidth: 4
    InnerUnroll: 1
    KernelLanguage: Assembly
    LSCA: 64
    LSCB: 32
    LSPA: 8
    LSPB: 8
    LVCA: 16
    LVCB: 16
    LVPA: 2
    LVPB: 4
    LdsNumElements: 1792
    LdsNumElementsAlignedA: 512
    LdsNumElementsAlignedB: 256
    LdsOffsetA: 0
    LdsOffsetA_Blk: 1024
    LdsOffsetB: 512
    LdsOffsetB_Blk: 1536
    LdsPadA: 0
    LdsPadB: 0
    LocalRead2A: true
    LocalRead2B: true
    LocalSplitU: 1
    LocalWrite2A: true
    LocalWrite2B: true
    LocalWriteUseSgprA: false
    LocalWriteUseSgprB: false
    LoopDoWhile: false
    LoopTail: true
    LoopUnroll: 8
    MacroTile0: 64
    MacroTile1: 32
    MacroTileA: 64
    MacroTileB: 32
    MacroTileShapeMax: 64
    MacroTileShapeMin: 1
    MaxOccupancy: 40
    MinGlobalWriteVectorWidth: 2
    NonTemporalA: 0
    NonTemporalB: 0
    NonTemporalC: 0
    NumElementsPerThread: 16
    NumGlobalWriteVectorsPerThread: 4
    NumLoadsCoalescedA: 1
    NumLoadsCoalescedB: 1
    NumLoadsPerpendicularA: 1
    NumLoadsPerpendicularB: 1
    NumThreads: 128
    PerformanceSyncLocation: -1
    PerformanceWaitCount: -1
    PerformanceWaitLocation: -1
    PersistentKernel: 0
    PreciseBoundsCheck: false
    PrefetchGlobalRead: true
    PrefetchLocalRead: true
    ProblemType:
      AssignedDerivedParameters: true
      Batched: true
      ComplexConjugateA: false
      ComplexConjugateB: false
      DataType: 4
      HighPrecisionAccumulate: false
      Index0: 0
      Index01A: 0
      Index01B: 1
      Index1: 1
      IndexAssignmentsA: [0, 3, 2]
      IndexAssignmentsB: [1, 3, 2]
      IndexUnroll: 3
      IndexUnrollA: 1
      IndexUnrollB: 1
      IndicesBatch: [2]
      IndicesFree: [0, 1]
      IndicesSummation: [3]
      NumIndicesBatch: 1
      NumIndicesC: 3
      NumIndicesFree: 2
      NumIndicesSummation: 1
      OperationType: GEMM
      SilentHighPrecisionAccumulate: false
      TLUA: true
      TLUB: true
      Tensor0: 0
      Tensor1: 1
      TileA: 0
      TileB: 1
      TotalIndices: 4
      TransposeA: false
      TransposeB: true
      UseBeta: true
      UseInitialStrides: false
    SolutionIndex: 2
    SolutionNameMin: Cijk_Ailk_Bjlk_HB_MT064x032x08_GRVW08_PGR1_PLR1_TT04_04_VW04_WG16_08_01_WGM01
    SubGroup0: 16
    SubGroup1: 8
    SubGroupA: 16
    SubGroupB: 8
    ThreadTile: [4, 4]
    ThreadTile0: 4
    ThreadTile1: 4
    ThreadTileA: 4
    ThreadTileB: 4
    UnrollMemFence: false
    UseSgprForGRO: 0
    Valid: true
    VectorStore: true
    VectorWidth: 4
    WorkGroup: [16, 8, 1]
    WorkGroupMapping: 1
    WorkGroupMappingType: B
    fractionalPerpOverhangA: 0
    fractionalPerpOverhangB: 0
  - AssertSummationElementMultiple: 1
    AssignedDerivedParameters: true
    AssignedProblemIndependentDerivedParameters: true
    BufferLoad: true
    BufferStore: true
    DepthU: 16
    DirectToLds: false
    DirectToLdsA: false
    DirectToLdsB: false
    DisableKernelPieces: 0
    EdgeType: ShiftPtr
    FractionalLoad: 1
    GlobalLoadVectorWidthA: 8
    GlobalLoadVectorWidthB: 4
    GlobalRead2A: true
    GlobalRead2B: true
    GlobalReadCoalesceGroupA: true
    GlobalReadCoalesceGroupB: true
    GlobalReadCoalesceVectorA: true
    GlobalReadCoalesceVectorB: true
    GlobalReadVectorWidth: 8
    GlobalSplitU: 1
    GlobalSplitUSummationAssignmentRoundRobin: true
    GlobalSplitUWorkGroupMappingRoundRobin: false
    GlobalWriteVectorWidth: 4
    InnerUnroll: 1
    KernelLanguage: Assembly
    LSCA: 64
    LSCB: 32
    LSPA: 16
    LSPB: 16
    LVCA: 8
    LVCB: 8
    LVPA: 2
    LVPB: 4
    LdsNumElements: 3584
    LdsNumElementsAlignedA: 1024
    LdsNumElementsAlignedB: 512
    LdsOffsetA: 0
    LdsOffsetA_Blk: 2048
    LdsOffsetB: 1024
    LdsOffsetB_Blk: 3072
    LdsPadA: 0
    LdsPadB: 0
    LocalRead2A: true
    LocalRead2B: true
    LocalSplitU: 1
    LocalWrite2A: true
    LocalWrite2B: true
    LocalWriteUseSgprA: false
    LocalWriteUseSgprB: false
    LoopDoWhile: false
    LoopTail: true
    LoopUnroll: 16
    MacroTile0: 64
    MacroTile1: 32
    MacroTileA: 64
    MacroTileB: 32
    MacroTileShapeMax: 64
    MacroTileShapeMin: 1
    MaxOccupancy: 40
    MinGlobalWriteVectorWidth: 2
    NonTemporalA: 0
    NonTemporalB: 0
    NonTemporalC: 0
    NumElementsPerThread: 16
    NumGlobalWriteVectorsPerThread: 4
    NumLoadsCoalescedA: 1
    NumLoadsCoalescedB: 1
    NumLoadsPerpendicularA: 1
    NumLoadsPerpendicularB: 1
    NumThreads: 128
    PerformanceSyncLocation: -1
    PerformanceWaitCount: -1
    PerformanceWaitLocation: -1
    PersistentKernel: 0
    PreciseBoundsCheck: false
    PrefetchGlobalRead: true
    PrefetchLocalRead: true
    ProblemType:
      AssignedDerivedParameters: true
      Batched: true
      ComplexConjugateA: false
      ComplexConjugateB: false
      DataType: 4
      HighPrecisionAccumulate: false
      Index0: 0
      Index01A: 0
      Index01B: 1
      Index1: 1
      IndexAssignmentsA: [0, 3, 2]
      IndexAssignmentsB: [1, 3, 2]
      IndexUnroll: 3
      IndexUnrollA: 1
      IndexUnrollB: 1
      IndicesBatch: [2]
      IndicesFree: [0, 1]
      IndicesSummation: [3]
      NumIndicesBatch: 1
      NumIndicesC: 3
      NumIndicesFree: 2
      NumIndicesSummation: 1
      OperationType: GEMM
      SilentHighPrecisionAccumulate: false
      TLUA: true
      TLUB: true
      Tensor0: 0
      Tensor1: 1
      TileA: 0
      TileB: 1
      TotalIndices: 4
      TransposeA: false
      TransposeB: true
      UseBeta: true
      UseInitialStrides: false
    SolutionIndex: 3
    SolutionNameMin: Cijk_Ailk_Bjlk_HB_MT064x032x16_GRVW08_PGR1_PLR1_TT04_04_VW04_WG16_08_01_WGM01
    SubGroup0: 16
    SubGroup1: 8
    SubGroupA: 16
    SubGroupB: 8
    ThreadTile: [4, 4]
    ThreadTile0: 4
    ThreadTile1: 4
    ThreadTileA: 4
    ThreadTileB: 4
    UnrollMemFence: false
    UseSgprForGRO: 0
    Valid: true
    VectorStore: true
    VectorWidth: 4
    WorkGroup: [16, 8, 1]
    WorkGroupMapping: 1
    WorkGroupMappingType: B
    fractionalPerpOverhangA: 0
    fractionalPerpOverhangB: 0
  - AssertSummationElementMultiple: 1
    AssignedDerivedParameters: true
    AssignedProblemIndependentDerivedParameters: true
    BufferLoad: true
    BufferStore: true
    DepthU: 16
    DirectToLds: false
    DirectToLdsA: false
    DirectToLdsB: false
    DisableKernelPieces: 0
    EdgeType: ShiftPtr
    FractionalLoad: 1
    GlobalLoadVectorWidthA: 2
    GlobalLoadVectorWidthB: 2
    GlobalRead2A: true
    GlobalRead2B: true
    GlobalReadCoalesceGroupA: true
    GlobalReadCoalesceGroupB: true
    GlobalReadCoalesceVectorA: true
    GlobalReadCoalesceVectorB: true
    GlobalReadVectorWidth: 2
    GlobalSplitU: 1
    GlobalSplitUSummationAssignmentRoundRobin: true
    GlobalSplitUWorkGroupMappingRoundRobin: false
    GlobalWriteVectorWidth: 4
    InnerUnroll: 1
    KernelLanguage: Assembly
    LSCA: 64
    LSCB: 32
    LSPA: 4
    LSPB: 8
    LVCA: 32
    LVCB: 16
    LVPA: 2
    LVPB: 4
    LdsNumElements: 3584
    LdsNumElementsAlignedA: 1024
    LdsNumElementsAlignedB: 512
    LdsOffsetA: 0
    LdsOffsetA_Blk: 2048
    LdsOffsetB: 1024
    LdsOffsetB_Blk: 3072
    LdsPadA: 0
    LdsPadB: 0
    LocalRead2A: true
    LocalRead2B: true
    LocalSplitU: 1
    LocalWrite2A: true
    LocalWrite2B: true
    LocalWriteUseSgprA: false
    LocalWriteUseSgprB: false
    LoopDoWhile: false
    LoopTail: true
    LoopUnroll: 16
    MacroTile0: 64
    MacroTile1: 32
    MacroTileA: 64
    MacroTileB: 32
    MacroTileShapeMax: 64
    MacroTileShapeMin: 1
    MaxOccupancy: 40
    MinGlobalWriteVectorWidth: 2
    NonTemporalA: 0
    NonTemporalB: 0
    NonTemporalC: 0
    NumElementsPerThread: 16
    NumGlobalWriteVectorsPerThread: 4
    NumLoadsCoalescedA: 1
    NumLoadsCoalescedB: 1
    NumLoadsPerpendicularA: 4
    NumLoadsPerpendicularB: 2
    NumThreads: 128
    PerformanceSyncLocation: -1
    PerformanceWaitCount: -1
    PerformanceWaitLocation: -1
    PersistentKernel: 0
    PreciseBoundsCheck: false
    PrefetchGlobalRead: true
    PrefetchLocalRead: true
    ProblemType:
      AssignedDerivedParameters: true
      Batched: true
      ComplexConjugateA: false
      ComplexConjugateB: false
      DataType: 4
      HighPrecisionAccumulate: false
      Index0: 0
      Index01A: 0
      Index01B: 1
      Index1: 1
      IndexAssignmentsA: [0, 3, 2]
      IndexAssignmentsB: [1, 3, 2]
      IndexUnroll: 3
      IndexUnrollA: 1
      IndexUnrollB: 1
      IndicesBatch: [2]
      IndicesFree: [0, 1]
      IndicesSummation: [3]
      NumIndicesBatch: 1
      NumIndicesC: 3
      NumIndicesFree: 2
      NumIndicesSummation: 1
      OperationType: GEMM
      SilentHighPrecisionAccumulate: false
      TLUA: true
      TLUB: true
      Tensor0: 0
      Tensor1: 1
      TileA: 0
      TileB: 1
      TotalIndices: 4
      TransposeA: false
      TransposeB: true
      UseBeta: true
      UseInitialStrides: false
    SolutionIndex: 4
    SolutionNameMin: Cijk_Ailk_Bjlk_HB_MT064x032x16_GRVW02_PGR1_PLR1_TT04_04_VW04_WG16_08_01_WGM01
    SubGroup0: 16
    SubGroup1: 8
    SubGroupA: 16
    SubGroupB: 8
    ThreadTile: [4, 4]
    ThreadTile0: 4
    ThreadTile1: 4
    ThreadTileA: 4
    ThreadTileB: 4
    UnrollMemFence: false
    UseSgprForGRO: 0
    Valid: true
    VectorStore: true
    VectorWidth: 4
    WorkGroup: [16, 8, 1]
    WorkGroupMapping: 1
    WorkGroupMappingType: B
    fractionalPerpOverhangA: 0
    fractionalPerpOverhangB: 0
- [2, 3, 0, 1]
- - - [1024, 32, 1, 512]
    - [3, 883.621]
  - - [2560, 7133, 1, 2560]
    - [0, 21604.6]
  - - [4096, 7133, 1, 4096]
    - [1, 22441.6]
  - - [512, 32, 1, 512]
    - [2, 433.676]
  - - [3072, 7435, 1, 1024]
    - [1, 20080.2]
  - - [1024, 16, 1, 512]
    - [3, 422.806]
  - - [1760, 7133, 1, 1760]
    - [1, 18916.7]
  - - [2048, 7133, 1, 2048]
    - [1, 21776.0]
  - - [7680, 5481, 1, 2560]
    - [1, 21933.0]
  - - [512, 16, 1, 512]
    - [4, 206.224]
- null
