- {MinimumRequiredVersion: 4.18.0}
- vega20
- gfx906
- [Device 66a0, Device 66a1, Device 66a7, Vega 20]
- AllowNoFreeDims: false
  AssignedDerivedParameters: true
  Batched: false
  ComplexConjugateA: false
  ComplexConjugateB: false
  ComputeDataType: 0
  ConvolutionConfig:
  - {Dilation: 1x1}
  - {Filter: 1x1}
  - {Stride: 2x2}
  - {TensorAFormat: NCHW}
  DataType: 0
  DestDataType: 0
  HighPrecisionAccumulate: false
  Index0: 0
  Index01A: 0
  Index01B: 2
  Index1: 2
  IndexAssignmentsA: [0, 1, 4, 3]
  IndexAssignmentsB: [2, 4, 3]
  IndexAssignmentsLD: [3, 4, 5, 6]
  IndexUnroll: 4
  IndexUnrollA: 2
  IndexUnrollB: 1
  IndicesBatch: [3]
  IndicesFree: [0, 1, 2]
  IndicesSummation: [4]
  NumIndicesBatch: 1
  NumIndicesC: 4
  NumIndicesFree: 3
  NumIndicesLD: 0
  NumIndicesSummation: 1
  OperationType: ConvolutionBackwardData
  SetConstStrideA:
  - [0, 2]
  SetConstStrideB:
  - [2, 1]
  - [3, 0]
  SilentHighPrecisionAccumulate: false
  TLUA: true
  TLUB: true
  Tensor0: 0
  Tensor1: 1
  TileA: 0
  TileAwareSelection: false
  TileB: 1
  TotalIndices: 5
  TransposeA: false
  TransposeB: true
  UseBeta: false
  UseInitialStridesAB: true
  UseInitialStridesCD: false
  ZeroPadA: []
  ZeroPadB: []
- - AggressivePerfMode: 1
    AssertFree0ElementMultiple: 4
    AssertFree1ElementMultiple: 1
    AssertMinApproxSize: 0
    AssertSizeEqual: {}
    AssertStrideAEqual: {0: 2}
    AssertStrideBEqual: {0: 1, 2: 0}
    AssertStrideCEqual: {0: 1}
    AssertStrideDEqual: {0: 1}
    AssertSummationElementMultiple: 1
    AssignedDerivedParameters: false
    AssignedProblemIndependentDerivedParameters: true
    BufferLoad: true
    BufferStore: true
    CheckDimOverflow: 0
    CheckTensorDimAsserts: false
    DepthU: 4
    DirectToLds: false
    DirectToLdsA: false
    DirectToLdsB: false
    DisableAtomicFail: 0
    DisableKernelPieces: 0
    EdgeType: ShiftPtr
    ExpandPointerSwap: 1
    FractionalLoad: 1
    GlobalLoadVectorWidthA: 1
    GlobalLoadVectorWidthB: 1
    GlobalRead2A: true
    GlobalRead2B: true
    GlobalReadCoalesceGroupA: true
    GlobalReadCoalesceGroupB: true
    GlobalReadCoalesceVectorA: true
    GlobalReadCoalesceVectorB: true
    GlobalReadVectorWidth: 1
    GlobalSplitU: 1
    GlobalSplitUSummationAssignmentRoundRobin: true
    GlobalSplitUWorkGroupMappingRoundRobin: false
    GlobalWriteVectorWidth: 1
    GuaranteeNoPartialA: true
    GuaranteeNoPartialB: true
    ISA: [9, 0, 6]
    InnerUnroll: 1
    InterleaveAlpha: 0
    KernelLanguage: Assembly
    LSCA: 48
    LSCB: 128
    LSPA: 2
    LSPB: 1
    LVCA: 48
    LVCB: 128
    LVPA: 2
    LVPB: 1
    LdcEqualsLdd: true
    LdsBlockSizePerPad: -1
    LdsNumElements: 1728
    LdsNumElementsAlignedA: 192
    LdsNumElementsAlignedB: 512
    LdsOffsetA: 0
    LdsOffsetA_Blk: 1024
    LdsOffsetB: 192
    LdsOffsetB_Blk: 1216
    LdsPadA: 0
    LdsPadB: 0
    LocalDotLayout: 1
    LocalRead2A: true
    LocalRead2B: true
    LocalReadVectorWidth: -1
    LocalSplitU: 1
    LocalWrite2A: true
    LocalWrite2B: true
    LocalWriteUseSgprA: false
    LocalWriteUseSgprB: false
    LoopDoWhile: false
    LoopIters: 4
    LoopTail: true
    LoopUnroll: 4
    MacroTile0: 48
    MacroTile1: 128
    MacroTileA: 48
    MacroTileB: 128
    MacroTileShapeMax: 64
    MacroTileShapeMin: 1
    MagicDivAlg: 2
    MatrixInstruction: []
    MaxOccupancy: 40
    MaxVgprNumber: 256
    MinVgprNumber: 0
    NonTemporalA: 0
    NonTemporalB: 0
    NonTemporalC: 0
    NumElementsPerThread: 48
    NumGlobalWriteVectorsPerThread: 48
    NumLoadsCoalescedA: 1
    NumLoadsCoalescedB: 1
    NumLoadsPerpendicularA: 2
    NumLoadsPerpendicularB: 4
    NumThreads: 128
    OptNoLoadLoop: 1
    PackBatchDims: 0
    PackFreeDims: 1
    PackGranularity: 2
    PackSummationDims: 0
    PackedC0IdxChars: [I, J]
    PackedC0IndicesX: [0, 1]
    PackedC1IdxChars: [K]
    PackedC1IndicesX: [2]
    PerformanceSyncLocation: -1
    PerformanceWaitCount: -1
    PerformanceWaitLocation: -1
    PersistentKernel: 0
    PrefetchAcrossPersistent: 0
    PrefetchGlobalRead: 1
    PrefetchLocalRead: 1
    ProblemType:
      AllowNoFreeDims: false
      AssignedDerivedParameters: true
      Batched: false
      ComplexConjugateA: false
      ComplexConjugateB: false
      ComputeDataType: 0
      ConvolutionConfig:
      - {Dilation: 1x1}
      - {Filter: 1x1}
      - {Stride: 2x2}
      - {TensorAFormat: NCHW}
      DataType: 0
      DestDataType: 0
      HighPrecisionAccumulate: false
      Index0: 0
      Index01A: 0
      Index01B: 2
      Index1: 2
      IndexAssignmentsA: [0, 1, 4, 3]
      IndexAssignmentsB: [2, 4, 3]
      IndexAssignmentsLD: [3, 4, 5, 6]
      IndexUnroll: 4
      IndexUnrollA: 2
      IndexUnrollB: 1
      IndicesBatch: [3]
      IndicesFree: [0, 1, 2]
      IndicesSummation: [4]
      NumIndicesBatch: 1
      NumIndicesC: 4
      NumIndicesFree: 3
      NumIndicesLD: 0
      NumIndicesSummation: 1
      OperationType: ConvolutionBackwardData
      SetConstStrideA:
      - [0, 2]
      SetConstStrideB:
      - [2, 1]
      - [3, 0]
      SilentHighPrecisionAccumulate: false
      TLUA: true
      TLUB: true
      Tensor0: 0
      Tensor1: 1
      TileA: 0
      TileAwareSelection: false
      TileB: 1
      TotalIndices: 5
      TransposeA: false
      TransposeB: true
      UseBeta: false
      UseInitialStridesAB: true
      UseInitialStridesCD: false
      ZeroPadA: []
      ZeroPadB: []
    ReplacementKernel: false
    ScheduleGlobalRead: 1
    ScheduleIterAlg: 1
    ScheduleLocalWrite: 1
    StaggerU: 0
    StaggerUMapping: 0
    StaggerUStride: 256
    StoreVectorWidth: 4
    SubGroup0: 8
    SubGroup1: 16
    SubGroupA: 8
    SubGroupB: 16
    SuppressNoLoadLoop: false
    ThreadTile: [6, 8]
    ThreadTile0: 6
    ThreadTile1: 8
    ThreadTileA: 6
    ThreadTileB: 8
    TransposeLDS: 0
    UnrollIncIsDepthU: 0
    UnrollMemFence: false
    Use64bShadowLimit: 1
    UseInstOffsetForGRO: 0
    UseSgprForGRO: -1
    Valid: true
    VectorAtomicWidth: 1
    VectorStore: -1
    VectorWidth: 1
    WorkGroup: [8, 16, 1]
    WorkGroupMapping: 1
    WorkGroupMappingType: B
    _UseSgprForGRO: 0
    _VectorStore: 1
    _staggerStrideShift: 4
    fractionalPerpOverhangA: 0
    fractionalPerpOverhangB: 0
- [1, 3, 4, 0, 2]
- - - [28, 28, 256, 64, 512]
    - [0, 13153337344.0]
  - - [14, 14, 512, 64, 1024]
    - [0, 13153337344.0]
  - - [14, 14, 512, 64, 256]
    - [0, 3288334336.0]
  - - [7, 7, 1024, 64, 2048]
    - [0, 13153337344.0]
  - - [7, 7, 1024, 64, 512]
    - [0, 3288334336.0]
- null
