- {MinimumRequiredVersion: 4.18.0}
- vega20
- gfx906
- [Device 66a0, Device 66a1, Device 66a7, Vega 20]
- AllowNoFreeDims: false
  AssignedDerivedParameters: true
  Batched: false
  ComplexConjugateA: false
  ComplexConjugateB: false
  ComputeDataType: 0
  ConvolutionConfig:
  - {Dilation: 1x1}
  - {Filter: 1x1}
  - {Stride: 1x1}
  - {TensorAFormat: NCHW}
  DataType: 0
  DestDataType: 0
  HighPrecisionAccumulate: false
  Index0: 0
  Index01A: 0
  Index01B: 1
  Index1: 1
  IndexAssignmentsA: [0, 3, 2]
  IndexAssignmentsB: [1, 3, 2]
  IndexAssignmentsLD: [3, 4, 5, 6]
  IndexUnroll: 3
  IndexUnrollA: 1
  IndexUnrollB: 1
  IndicesBatch: [2]
  IndicesFree: [0, 1]
  IndicesSummation: [3]
  NumIndicesBatch: 1
  NumIndicesC: 3
  NumIndicesFree: 2
  NumIndicesLD: 0
  NumIndicesSummation: 1
  OperationType: ConvolutionBackwardData
  SetConstStrideA:
  - [0, 1]
  SetConstStrideB:
  - [1, 1]
  - [2, 0]
  SilentHighPrecisionAccumulate: false
  TLUA: true
  TLUB: true
  Tensor0: 0
  Tensor1: 1
  TileA: 0
  TileAwareSelection: false
  TileB: 1
  TotalIndices: 4
  TransposeA: false
  TransposeB: true
  UseBeta: false
  UseInitialStridesAB: false
  UseInitialStridesCD: false
  ZeroPadA: []
  ZeroPadB: []
- - AggressivePerfMode: 1
    AssertFree0ElementMultiple: 4
    AssertFree1ElementMultiple: 1
    AssertMinApproxSize: 0
    AssertSizeEqual: {}
    AssertStrideAEqual: {0: 1}
    AssertStrideBEqual: {0: 1, 2: 0}
    AssertStrideCEqual: {0: 1}
    AssertStrideDEqual: {0: 1}
    AssertSummationElementMultiple: 1
    AssignedDerivedParameters: false
    AssignedProblemIndependentDerivedParameters: true
    BufferLoad: true
    BufferStore: true
    CheckDimOverflow: 0
    CheckTensorDimAsserts: false
    DepthU: 4
    DirectToLds: false
    DirectToLdsA: false
    DirectToLdsB: false
    DisableAtomicFail: 0
    DisableKernelPieces: 0
    EdgeType: ShiftPtr
    ExpandPointerSwap: 1
    FractionalLoad: 1
    GlobalLoadVectorWidthA: 1
    GlobalLoadVectorWidthB: 1
    GlobalRead2A: true
    GlobalRead2B: true
    GlobalReadCoalesceGroupA: true
    GlobalReadCoalesceGroupB: true
    GlobalReadCoalesceVectorA: true
    GlobalReadCoalesceVectorB: true
    GlobalReadVectorWidth: 1
    GlobalSplitU: 1
    GlobalSplitUSummationAssignmentRoundRobin: true
    GlobalSplitUWorkGroupMappingRoundRobin: false
    GlobalWriteVectorWidth: 1
    GuaranteeNoPartialA: true
    GuaranteeNoPartialB: true
    ISA: [9, 0, 6]
    InnerUnroll: 1
    InterleaveAlpha: 0
    KernelLanguage: Assembly
    LSCA: 48
    LSCB: 128
    LSPA: 2
    LSPB: 1
    LVCA: 48
    LVCB: 128
    LVPA: 2
    LVPB: 1
    LdcEqualsLdd: true
    LdsBlockSizePerPad: -1
    LdsNumElements: 1728
    LdsNumElementsAlignedA: 192
    LdsNumElementsAlignedB: 512
    LdsOffsetA: 0
    LdsOffsetA_Blk: 1024
    LdsOffsetB: 192
    LdsOffsetB_Blk: 1216
    LdsPadA: 0
    LdsPadB: 0
    LocalDotLayout: 1
    LocalRead2A: true
    LocalRead2B: true
    LocalReadVectorWidth: -1
    LocalSplitU: 1
    LocalWrite2A: true
    LocalWrite2B: true
    LocalWriteUseSgprA: false
    LocalWriteUseSgprB: false
    LoopDoWhile: false
    LoopIters: 4
    LoopTail: true
    LoopUnroll: 4
    MacroTile0: 48
    MacroTile1: 128
    MacroTileA: 48
    MacroTileB: 128
    MacroTileShapeMax: 64
    MacroTileShapeMin: 1
    MagicDivAlg: 2
    MatrixInstruction: []
    MaxOccupancy: 40
    MaxVgprNumber: 256
    MinVgprNumber: 0
    NonTemporalA: 0
    NonTemporalB: 0
    NonTemporalC: 0
    NumElementsPerThread: 48
    NumGlobalWriteVectorsPerThread: 48
    NumLoadsCoalescedA: 1
    NumLoadsCoalescedB: 1
    NumLoadsPerpendicularA: 2
    NumLoadsPerpendicularB: 4
    NumThreads: 128
    OptNoLoadLoop: 1
    PackBatchDims: 0
    PackFreeDims: 1
    PackGranularity: 2
    PackSummationDims: 0
    PackedC0IdxChars: [I]
    PackedC0IndicesX: [0]
    PackedC1IdxChars: [J]
    PackedC1IndicesX: [1]
    PerformanceSyncLocation: -1
    PerformanceWaitCount: -1
    PerformanceWaitLocation: -1
    PersistentKernel: 0
    PrefetchAcrossPersistent: 0
    PrefetchGlobalRead: 1
    PrefetchLocalRead: 1
    ProblemType:
      AllowNoFreeDims: false
      AssignedDerivedParameters: true
      Batched: false
      ComplexConjugateA: false
      ComplexConjugateB: false
      ComputeDataType: 0
      ConvolutionConfig:
      - {Dilation: 1x1}
      - {Filter: 1x1}
      - {Stride: 1x1}
      - {TensorAFormat: NCHW}
      DataType: 0
      DestDataType: 0
      HighPrecisionAccumulate: false
      Index0: 0
      Index01A: 0
      Index01B: 1
      Index1: 1
      IndexAssignmentsA: [0, 3, 2]
      IndexAssignmentsB: [1, 3, 2]
      IndexAssignmentsLD: [3, 4, 5, 6]
      IndexUnroll: 3
      IndexUnrollA: 1
      IndexUnrollB: 1
      IndicesBatch: [2]
      IndicesFree: [0, 1]
      IndicesSummation: [3]
      NumIndicesBatch: 1
      NumIndicesC: 3
      NumIndicesFree: 2
      NumIndicesLD: 0
      NumIndicesSummation: 1
      OperationType: ConvolutionBackwardData
      SetConstStrideA:
      - [0, 1]
      SetConstStrideB:
      - [1, 1]
      - [2, 0]
      SilentHighPrecisionAccumulate: false
      TLUA: true
      TLUB: true
      Tensor0: 0
      Tensor1: 1
      TileA: 0
      TileAwareSelection: false
      TileB: 1
      TotalIndices: 4
      TransposeA: false
      TransposeB: true
      UseBeta: false
      UseInitialStridesAB: false
      UseInitialStridesCD: false
      ZeroPadA: []
      ZeroPadB: []
    ReplacementKernel: false
    ScheduleGlobalRead: 1
    ScheduleIterAlg: 1
    ScheduleLocalWrite: 1
    StaggerU: 0
    StaggerUMapping: 0
    StaggerUStride: 256
    StoreVectorWidth: 4
    SubGroup0: 8
    SubGroup1: 16
    SubGroupA: 8
    SubGroupB: 16
    SuppressNoLoadLoop: false
    ThreadTile: [6, 8]
    ThreadTile0: 6
    ThreadTile1: 8
    ThreadTileA: 6
    ThreadTileB: 8
    TransposeLDS: 0
    UnrollIncIsDepthU: 0
    UnrollMemFence: false
    Use64bShadowLimit: 1
    UseInstOffsetForGRO: 0
    UseSgprForGRO: -1
    Valid: true
    VectorAtomicWidth: 1
    VectorStore: -1
    VectorWidth: 1
    WorkGroup: [8, 16, 1]
    WorkGroupMapping: 1
    WorkGroupMappingType: B
    _UseSgprForGRO: 1
    _VectorStore: 1
    _staggerStrideShift: 4
    fractionalPerpOverhangA: 0
    fractionalPerpOverhangB: 0
  - AggressivePerfMode: 1
    AssertFree0ElementMultiple: 1
    AssertFree1ElementMultiple: 1
    AssertMinApproxSize: 0
    AssertSizeEqual: {}
    AssertStrideAEqual: {0: 1}
    AssertStrideBEqual: {0: 1, 2: 0}
    AssertStrideCEqual: {0: 1}
    AssertStrideDEqual: {0: 1}
    AssertSummationElementMultiple: 1
    AssignedDerivedParameters: false
    AssignedProblemIndependentDerivedParameters: true
    BufferLoad: true
    BufferStore: true
    CheckDimOverflow: 0
    CheckTensorDimAsserts: false
    DepthU: 4
    DirectToLds: false
    DirectToLdsA: false
    DirectToLdsB: false
    DisableAtomicFail: 0
    DisableKernelPieces: 0
    EdgeType: ShiftPtr
    ExpandPointerSwap: 1
    FractionalLoad: 1
    GlobalLoadVectorWidthA: 1
    GlobalLoadVectorWidthB: 1
    GlobalRead2A: true
    GlobalRead2B: true
    GlobalReadCoalesceGroupA: true
    GlobalReadCoalesceGroupB: true
    GlobalReadCoalesceVectorA: true
    GlobalReadCoalesceVectorB: true
    GlobalReadVectorWidth: 1
    GlobalSplitU: 1
    GlobalSplitUSummationAssignmentRoundRobin: true
    GlobalSplitUWorkGroupMappingRoundRobin: false
    GlobalWriteVectorWidth: 1
    GuaranteeNoPartialA: true
    GuaranteeNoPartialB: true
    ISA: [9, 0, 6]
    InnerUnroll: 1
    InterleaveAlpha: 0
    KernelLanguage: Assembly
    LSCA: 48
    LSCB: 128
    LSPA: 2
    LSPB: 1
    LVCA: 48
    LVCB: 128
    LVPA: 2
    LVPB: 1
    LdcEqualsLdd: true
    LdsBlockSizePerPad: -1
    LdsNumElements: 1728
    LdsNumElementsAlignedA: 192
    LdsNumElementsAlignedB: 512
    LdsOffsetA: 0
    LdsOffsetA_Blk: 1024
    LdsOffsetB: 192
    LdsOffsetB_Blk: 1216
    LdsPadA: 0
    LdsPadB: 0
    LocalDotLayout: 1
    LocalRead2A: true
    LocalRead2B: true
    LocalReadVectorWidth: -1
    LocalSplitU: 1
    LocalWrite2A: true
    LocalWrite2B: true
    LocalWriteUseSgprA: false
    LocalWriteUseSgprB: false
    LoopDoWhile: false
    LoopIters: 4
    LoopTail: true
    LoopUnroll: 4
    MacroTile0: 48
    MacroTile1: 128
    MacroTileA: 48
    MacroTileB: 128
    MacroTileShapeMax: 64
    MacroTileShapeMin: 1
    MagicDivAlg: 2
    MatrixInstruction: []
    MaxOccupancy: 40
    MaxVgprNumber: 256
    MinVgprNumber: 0
    NonTemporalA: 0
    NonTemporalB: 0
    NonTemporalC: 0
    NumElementsPerThread: 48
    NumGlobalWriteVectorsPerThread: 48
    NumLoadsCoalescedA: 1
    NumLoadsCoalescedB: 1
    NumLoadsPerpendicularA: 2
    NumLoadsPerpendicularB: 4
    NumThreads: 128
    OptNoLoadLoop: 1
    PackBatchDims: 0
    PackFreeDims: 1
    PackGranularity: 2
    PackSummationDims: 0
    PackedC0IdxChars: [I]
    PackedC0IndicesX: [0]
    PackedC1IdxChars: [J]
    PackedC1IndicesX: [1]
    PerformanceSyncLocation: -1
    PerformanceWaitCount: -1
    PerformanceWaitLocation: -1
    PersistentKernel: 0
    PrefetchAcrossPersistent: 0
    PrefetchGlobalRead: 1
    PrefetchLocalRead: 1
    ProblemType:
      AllowNoFreeDims: false
      AssignedDerivedParameters: true
      Batched: false
      ComplexConjugateA: false
      ComplexConjugateB: false
      ComputeDataType: 0
      ConvolutionConfig:
      - {Dilation: 1x1}
      - {Filter: 1x1}
      - {Stride: 1x1}
      - {TensorAFormat: NCHW}
      DataType: 0
      DestDataType: 0
      HighPrecisionAccumulate: false
      Index0: 0
      Index01A: 0
      Index01B: 1
      Index1: 1
      IndexAssignmentsA: [0, 3, 2]
      IndexAssignmentsB: [1, 3, 2]
      IndexAssignmentsLD: [3, 4, 5, 6]
      IndexUnroll: 3
      IndexUnrollA: 1
      IndexUnrollB: 1
      IndicesBatch: [2]
      IndicesFree: [0, 1]
      IndicesSummation: [3]
      NumIndicesBatch: 1
      NumIndicesC: 3
      NumIndicesFree: 2
      NumIndicesLD: 0
      NumIndicesSummation: 1
      OperationType: ConvolutionBackwardData
      SetConstStrideA:
      - [0, 1]
      SetConstStrideB:
      - [1, 1]
      - [2, 0]
      SilentHighPrecisionAccumulate: false
      TLUA: true
      TLUB: true
      Tensor0: 0
      Tensor1: 1
      TileA: 0
      TileAwareSelection: false
      TileB: 1
      TotalIndices: 4
      TransposeA: false
      TransposeB: true
      UseBeta: false
      UseInitialStridesAB: false
      UseInitialStridesCD: false
      ZeroPadA: []
      ZeroPadB: []
    ReplacementKernel: false
    ScheduleGlobalRead: 1
    ScheduleIterAlg: 1
    ScheduleLocalWrite: 1
    StaggerU: 0
    StaggerUMapping: 0
    StaggerUStride: 256
    StoreVectorWidth: 4
    SubGroup0: 8
    SubGroup1: 16
    SubGroupA: 8
    SubGroupB: 16
    SuppressNoLoadLoop: false
    ThreadTile: [6, 8]
    ThreadTile0: 6
    ThreadTile1: 8
    ThreadTileA: 6
    ThreadTileB: 8
    TransposeLDS: 0
    UnrollIncIsDepthU: 0
    UnrollMemFence: false
    Use64bShadowLimit: 1
    UseInstOffsetForGRO: 0
    UseSgprForGRO: -1
    Valid: true
    VectorAtomicWidth: 1
    VectorStore: -1
    VectorWidth: 1
    WorkGroup: [8, 16, 1]
    WorkGroupMapping: 1
    WorkGroupMappingType: B
    _UseSgprForGRO: 1
    _VectorStore: 1
    _staggerStrideShift: 4
    fractionalPerpOverhangA: 0
    fractionalPerpOverhangB: 0
- [2, 3, 0, 1]
- - - [64, 1280, 64, 192]
    - [0, 2013265920.0]
  - - [64, 1280, 64, 320]
    - [0, 3355443200.0]
  - - [64, 1280, 64, 384]
    - [0, 4026531840.0]
  - - [64, 1280, 64, 448]
    - [0, 4697620480.0]
  - - [64, 2048, 64, 192]
    - [0, 3221225472.0]
  - - [64, 2048, 64, 320]
    - [0, 5368709120.0]
  - - [64, 2048, 64, 384]
    - [0, 6442450944.0]
  - - [64, 2048, 64, 448]
    - [0, 7516192768.0]
  - - [3136, 64, 64, 256]
    - [0, 6576668672.0]
  - - [3136, 64, 64, 64]
    - [0, 1644167168.0]
  - - [3136, 256, 64, 64]
    - [0, 6576668672.0]
  - - [784, 128, 64, 512]
    - [0, 6576668672.0]
  - - [784, 512, 64, 128]
    - [0, 6576668672.0]
  - - [196, 256, 64, 1024]
    - [0, 6576668672.0]
  - - [196, 1024, 64, 256]
    - [0, 6576668672.0]
  - - [1225, 192, 64, 32]
    - [1, 963379200.0]
  - - [1225, 192, 64, 48]
    - [1, 1445068800.0]
  - - [1225, 192, 64, 64]
    - [1, 1926758400.0]
  - - [1225, 256, 64, 48]
    - [1, 1926758400.0]
  - - [1225, 256, 64, 64]
    - [1, 2569011200.0]
  - - [1225, 288, 64, 48]
    - [1, 2167603200.0]
  - - [1225, 288, 64, 64]
    - [1, 2890137600.0]
  - - [5329, 64, 64, 80]
    - [1, 3492413440.0]
  - - [289, 768, 64, 128]
    - [1, 3636461568.0]
  - - [289, 768, 64, 160]
    - [1, 4545576960.0]
  - - [289, 768, 64, 192]
    - [1, 5454692352.0]
  - - [49, 512, 64, 2048]
    - [1, 6576668672.0]
  - - [49, 2048, 64, 512]
    - [1, 6576668672.0]
- null
