- {MinimumRequiredVersion: 4.13.0}
- vega10
- gfx900
- [Device 6863, Device 6862, Device 687f, Device 6860, Device 6861, 'Vega 10 XTX [Radeon
    Vega Frontier Edition]', 'Vega [Radeon RX Vega]']
- AssignedDerivedParameters: true
  Batched: true
  ComplexConjugateA: false
  ComplexConjugateB: false
  ComputeDataType: 0
  ConvolutionConfig: []
  DataType: 0
  DestDataType: 0
  HighPrecisionAccumulate: false
  Index0: 0
  Index01A: 0
  Index01B: 1
  Index1: 1
  IndexAssignmentsA: [0, 3, 2]
  IndexAssignmentsB: [3, 1, 2]
  IndexAssignmentsLD: [4, 5, 6, 7]
  IndexUnroll: 3
  IndexUnrollA: 1
  IndexUnrollB: 0
  IndicesBatch: [2]
  IndicesFree: [0, 1]
  IndicesSummation: [3]
  NumIndicesBatch: 1
  NumIndicesC: 3
  NumIndicesFree: 2
  NumIndicesLD: 4
  NumIndicesSummation: 1
  OperationType: GEMM
  SetConstStrideA: []
  SetConstStrideB: []
  SilentHighPrecisionAccumulate: false
  TLUA: true
  TLUB: false
  Tensor0: 0
  Tensor1: 1
  TileA: 0
  TileAwareSelection: false
  TileB: 1
  TotalIndices: 4
  TransposeA: false
  TransposeB: false
  UseBeta: true
  UseInitialStrides: false
  ZeroPadA: []
  ZeroPadB: []
- - AggressivePerfMode: 1
    AssertFree0ElementMultiple: 1
    AssertFree1ElementMultiple: 1
    AssertMinApproxSize: 3
    AssertSummationElementMultiple: 1
    AssignedDerivedParameters: false
    AssignedProblemIndependentDerivedParameters: true
    BufferLoad: true
    BufferStore: true
    CheckDimOverflow: 0
    CheckTensorDimAsserts: false
    DepthU: 16
    DirectToLds: false
    DirectToLdsA: false
    DirectToLdsB: false
    DisableAtomicFail: 0
    DisableKernelPieces: 0
    EdgeType: ShiftPtr
    ExpandPointerSwap: true
    FractionalLoad: 0
    GlobalLoadVectorWidthA: 2
    GlobalLoadVectorWidthB: 2
    GlobalRead2A: true
    GlobalRead2B: true
    GlobalReadCoalesceGroupA: true
    GlobalReadCoalesceGroupB: true
    GlobalReadCoalesceVectorA: true
    GlobalReadCoalesceVectorB: true
    GlobalReadVectorWidth: 2
    GlobalSplitU: 1
    GlobalSplitUSummationAssignmentRoundRobin: true
    GlobalSplitUWorkGroupMappingRoundRobin: false
    GlobalWriteVectorWidth: 2
    GuaranteeNoPartialA: false
    GuaranteeNoPartialB: true
    ISA: [9, 0, 0]
    InnerUnroll: 1
    InterleaveAlpha: 0
    KernelLanguage: Assembly
    LSCA: 32
    LSCB: 16
    LSPA: 16
    LSPB: 32
    LVCA: 16
    LVCB: 8
    LVPA: 8
    LVPB: 16
    LdcEqualsLdd: true
    LdsNumElements: 6656
    LdsNumElementsAlignedA: 1536
    LdsNumElementsAlignedB: 1024
    LdsOffsetA: 0
    LdsOffsetA_Blk: 4096
    LdsOffsetB: 1536
    LdsOffsetB_Blk: 5632
    LdsPadA: 0
    LdsPadB: 0
    LocalDotLayout: 1
    LocalRead2A: true
    LocalRead2B: true
    LocalSplitU: 1
    LocalWrite2A: true
    LocalWrite2B: true
    LocalWriteUseSgprA: false
    LocalWriteUseSgprB: false
    LoopDoWhile: false
    LoopTail: true
    LoopUnroll: 16
    MacroTile0: 96
    MacroTile1: 64
    MacroTileA: 96
    MacroTileB: 64
    MacroTileShapeMax: 64
    MacroTileShapeMin: 1
    MaxOccupancy: 40
    MaxVgprNumber: 256
    MinVgprNumber: 0
    NonTemporalA: 0
    NonTemporalB: 0
    NonTemporalC: 0
    NumElementsPerThread: 24
    NumGlobalWriteVectorsPerThread: 12
    NumLoadsA: 3
    NumLoadsB: 2
    NumLoadsCoalescedA: 3
    NumLoadsCoalescedB: 1
    NumLoadsPerpendicularA: 1
    NumLoadsPerpendicularB: 2
    NumThreads: 256
    OptNoLoadLoop: 1
    PackBatchDims: 0
    PackFreeDims: 1
    PackGranularity: 2
    PackedC0IdxChars: [I]
    PackedC0IndicesX: [0]
    PackedC1IdxChars: [J]
    PackedC1IndicesX: [1]
    PerformanceSyncLocation: -1
    PerformanceWaitCount: -1
    PerformanceWaitLocation: -1
    PersistentKernel: 0
    PrefetchAcrossPersistent: 0
    PrefetchGlobalRead: true
    PrefetchLocalRead: false
    ProblemType:
      AssignedDerivedParameters: true
      Batched: true
      ComplexConjugateA: false
      ComplexConjugateB: false
      ComputeDataType: 0
      ConvolutionConfig: []
      DataType: 0
      DestDataType: 0
      HighPrecisionAccumulate: false
      Index0: 0
      Index01A: 0
      Index01B: 1
      Index1: 1
      IndexAssignmentsA: [0, 3, 2]
      IndexAssignmentsB: [3, 1, 2]
      IndexAssignmentsLD: [4, 5, 6, 7]
      IndexUnroll: 3
      IndexUnrollA: 1
      IndexUnrollB: 0
      IndicesBatch: [2]
      IndicesFree: [0, 1]
      IndicesSummation: [3]
      NumIndicesBatch: 1
      NumIndicesC: 3
      NumIndicesFree: 2
      NumIndicesLD: 4
      NumIndicesSummation: 1
      OperationType: GEMM
      SetConstStrideA: []
      SetConstStrideB: []
      SilentHighPrecisionAccumulate: false
      TLUA: true
      TLUB: false
      Tensor0: 0
      Tensor1: 1
      TileA: 0
      TileAwareSelection: false
      TileB: 1
      TotalIndices: 4
      TransposeA: false
      TransposeB: false
      UseBeta: true
      UseInitialStrides: false
      ZeroPadA: []
      ZeroPadB: []
    ReplacementKernel: false
    ScheduleGlobalRead: 1
    ScheduleIterAlg: 1
    ScheduleLocalWrite: 1
    SolutionIndex: 0
    SolutionNameMin: Cijk_Ailk_Bljk_SB_MT96x64x16_SE_EPS1_FL0_GRVW2_NLCA3_PGR1_PLR0_TT6_4_USFGRO0_VW2_WGM8
    StaggerU: 32
    StaggerUMapping: 0
    StaggerUStride: 256
    SubGroup0: 16
    SubGroup1: 16
    SubGroupA: 16
    SubGroupB: 16
    SuppressNoLoadLoop: false
    ThreadTile: [6, 4]
    ThreadTile0: 6
    ThreadTile1: 4
    ThreadTileA: 6
    ThreadTileB: 4
    UnrollMemFence: false
    UseSgprForGRO: false
    Valid: true
    VectorAtomicWidth: 1
    VectorStore: true
    VectorWidth: 2
    WorkGroup: [16, 16, 1]
    WorkGroupMapping: 8
    WorkGroupMappingType: B
    _staggerStrideShift: 2
  - AggressivePerfMode: 1
    AssertFree0ElementMultiple: 1
    AssertFree1ElementMultiple: 1
    AssertMinApproxSize: 3
    AssertSummationElementMultiple: 1
    AssignedDerivedParameters: false
    AssignedProblemIndependentDerivedParameters: true
    BufferLoad: true
    BufferStore: true
    CheckDimOverflow: 0
    CheckTensorDimAsserts: false
    DepthU: 16
    DirectToLds: false
    DirectToLdsA: false
    DirectToLdsB: false
    DisableAtomicFail: 0
    DisableKernelPieces: 0
    EdgeType: ShiftPtr
    ExpandPointerSwap: true
    FractionalLoad: 0
    GlobalLoadVectorWidthA: 2
    GlobalLoadVectorWidthB: 2
    GlobalRead2A: true
    GlobalRead2B: true
    GlobalReadCoalesceGroupA: true
    GlobalReadCoalesceGroupB: true
    GlobalReadCoalesceVectorA: true
    GlobalReadCoalesceVectorB: true
    GlobalReadVectorWidth: 2
    GlobalSplitU: 1
    GlobalSplitUSummationAssignmentRoundRobin: true
    GlobalSplitUWorkGroupMappingRoundRobin: false
    GlobalWriteVectorWidth: 2
    GuaranteeNoPartialA: false
    GuaranteeNoPartialB: true
    ISA: [9, 0, 0]
    InnerUnroll: 1
    InterleaveAlpha: 0
    KernelLanguage: Assembly
    LSCA: 128
    LSCB: 16
    LSPA: 4
    LSPB: 32
    LVCA: 64
    LVCB: 8
    LVPA: 2
    LVPB: 16
    LdcEqualsLdd: true
    LdsNumElements: 8192
    LdsNumElementsAlignedA: 2048
    LdsNumElementsAlignedB: 2048
    LdsOffsetA: 0
    LdsOffsetA_Blk: 4096
    LdsOffsetB: 2048
    LdsOffsetB_Blk: 6144
    LdsPadA: 0
    LdsPadB: 0
    LocalDotLayout: 1
    LocalRead2A: true
    LocalRead2B: true
    LocalSplitU: 1
    LocalWrite2A: true
    LocalWrite2B: true
    LocalWriteUseSgprA: false
    LocalWriteUseSgprB: false
    LoopDoWhile: false
    LoopTail: true
    LoopUnroll: 16
    MacroTile0: 128
    MacroTile1: 128
    MacroTileA: 128
    MacroTileB: 128
    MacroTileShapeMax: 64
    MacroTileShapeMin: 1
    MaxOccupancy: 40
    MaxVgprNumber: 256
    MinVgprNumber: 0
    NonTemporalA: 0
    NonTemporalB: 0
    NonTemporalC: 0
    NumElementsPerThread: 64
    NumGlobalWriteVectorsPerThread: 32
    NumLoadsA: 4
    NumLoadsB: 4
    NumLoadsCoalescedA: 1
    NumLoadsCoalescedB: 1
    NumLoadsPerpendicularA: 4
    NumLoadsPerpendicularB: 4
    NumThreads: 256
    OptNoLoadLoop: 1
    PackBatchDims: 0
    PackFreeDims: 1
    PackGranularity: 2
    PackedC0IdxChars: [I]
    PackedC0IndicesX: [0]
    PackedC1IdxChars: [J]
    PackedC1IndicesX: [1]
    PerformanceSyncLocation: -1
    PerformanceWaitCount: -1
    PerformanceWaitLocation: -1
    PersistentKernel: 0
    PrefetchAcrossPersistent: 0
    PrefetchGlobalRead: true
    PrefetchLocalRead: true
    ProblemType:
      AssignedDerivedParameters: true
      Batched: true
      ComplexConjugateA: false
      ComplexConjugateB: false
      ComputeDataType: 0
      ConvolutionConfig: []
      DataType: 0
      DestDataType: 0
      HighPrecisionAccumulate: false
      Index0: 0
      Index01A: 0
      Index01B: 1
      Index1: 1
      IndexAssignmentsA: [0, 3, 2]
      IndexAssignmentsB: [3, 1, 2]
      IndexAssignmentsLD: [4, 5, 6, 7]
      IndexUnroll: 3
      IndexUnrollA: 1
      IndexUnrollB: 0
      IndicesBatch: [2]
      IndicesFree: [0, 1]
      IndicesSummation: [3]
      NumIndicesBatch: 1
      NumIndicesC: 3
      NumIndicesFree: 2
      NumIndicesLD: 4
      NumIndicesSummation: 1
      OperationType: GEMM
      SetConstStrideA: []
      SetConstStrideB: []
      SilentHighPrecisionAccumulate: false
      TLUA: true
      TLUB: false
      Tensor0: 0
      Tensor1: 1
      TileA: 0
      TileAwareSelection: false
      TileB: 1
      TotalIndices: 4
      TransposeA: false
      TransposeB: false
      UseBeta: true
      UseInitialStrides: false
      ZeroPadA: []
      ZeroPadB: []
    ReplacementKernel: false
    ScheduleGlobalRead: 1
    ScheduleIterAlg: 1
    ScheduleLocalWrite: 1
    SolutionIndex: 1
    SolutionNameMin: Cijk_Ailk_Bljk_SB_MT128x128x16_SE_EPS1_FL0_GRVW2_NLCA1_PGR1_PLR1_TT8_8_USFGRO0_VW2_WGM1
    StaggerU: 32
    StaggerUMapping: 0
    StaggerUStride: 256
    SubGroup0: 16
    SubGroup1: 16
    SubGroupA: 16
    SubGroupB: 16
    SuppressNoLoadLoop: false
    ThreadTile: [8, 8]
    ThreadTile0: 8
    ThreadTile1: 8
    ThreadTileA: 8
    ThreadTileB: 8
    UnrollMemFence: false
    UseSgprForGRO: false
    Valid: true
    VectorAtomicWidth: 1
    VectorStore: true
    VectorWidth: 2
    WorkGroup: [16, 16, 1]
    WorkGroupMapping: 1
    WorkGroupMappingType: B
    _staggerStrideShift: 2
  - AggressivePerfMode: 1
    AssertFree0ElementMultiple: 1
    AssertFree1ElementMultiple: 1
    AssertMinApproxSize: 3
    AssertSummationElementMultiple: 1
    AssignedDerivedParameters: false
    AssignedProblemIndependentDerivedParameters: true
    BufferLoad: true
    BufferStore: true
    CheckDimOverflow: 0
    CheckTensorDimAsserts: false
    DepthU: 32
    DirectToLds: false
    DirectToLdsA: false
    DirectToLdsB: false
    DisableAtomicFail: 0
    DisableKernelPieces: 0
    EdgeType: ShiftPtr
    ExpandPointerSwap: true
    FractionalLoad: 1
    GlobalLoadVectorWidthA: 2
    GlobalLoadVectorWidthB: 4
    GlobalRead2A: true
    GlobalRead2B: true
    GlobalReadCoalesceGroupA: true
    GlobalReadCoalesceGroupB: true
    GlobalReadCoalesceVectorA: true
    GlobalReadCoalesceVectorB: true
    GlobalReadVectorWidth: 4
    GlobalSplitU: 1
    GlobalSplitUSummationAssignmentRoundRobin: true
    GlobalSplitUWorkGroupMappingRoundRobin: false
    GlobalWriteVectorWidth: 2
    GuaranteeNoPartialA: false
    GuaranteeNoPartialB: true
    ISA: [9, 0, 0]
    InnerUnroll: 1
    InterleaveAlpha: 0
    KernelLanguage: Assembly
    LSCA: 16
    LSCB: 32
    LSPA: 32
    LSPB: 32
    LVCA: 8
    LVCB: 8
    LVPA: 16
    LVPB: 8
    LdcEqualsLdd: true
    LdsNumElements: 3648
    LdsNumElementsAlignedA: 512
    LdsNumElementsAlignedB: 1088
    LdsOffsetA: 0
    LdsOffsetA_Blk: 2048
    LdsOffsetB: 512
    LdsOffsetB_Blk: 2560
    LdsPadA: 0
    LdsPadB: 2
    LocalDotLayout: 1
    LocalRead2A: true
    LocalRead2B: true
    LocalSplitU: 2
    LocalWrite2A: true
    LocalWrite2B: true
    LocalWriteUseSgprA: false
    LocalWriteUseSgprB: false
    LoopDoWhile: false
    LoopTail: true
    LoopUnroll: 16
    MacroTile0: 16
    MacroTile1: 32
    MacroTileA: 16
    MacroTileB: 32
    MacroTileShapeMax: 64
    MacroTileShapeMin: 1
    MaxOccupancy: 40
    MaxVgprNumber: 256
    MinVgprNumber: 0
    NonTemporalA: 0
    NonTemporalB: 0
    NonTemporalC: 0
    NumElementsPerThread: 2
    NumGlobalWriteVectorsPerThread: 1
    NumLoadsCoalescedA: 1
    NumLoadsCoalescedB: 1
    NumLoadsPerpendicularA: 1
    NumLoadsPerpendicularB: 1
    NumThreads: 256
    OptNoLoadLoop: 1
    PackBatchDims: 0
    PackFreeDims: 1
    PackGranularity: 2
    PackedC0IdxChars: [I]
    PackedC0IndicesX: [0]
    PackedC1IdxChars: [J]
    PackedC1IndicesX: [1]
    PerformanceSyncLocation: -1
    PerformanceWaitCount: -1
    PerformanceWaitLocation: -1
    PersistentKernel: 0
    PrefetchAcrossPersistent: 0
    PrefetchGlobalRead: true
    PrefetchLocalRead: true
    ProblemType:
      AssignedDerivedParameters: true
      Batched: true
      ComplexConjugateA: false
      ComplexConjugateB: false
      ComputeDataType: 0
      ConvolutionConfig: []
      DataType: 0
      DestDataType: 0
      HighPrecisionAccumulate: false
      Index0: 0
      Index01A: 0
      Index01B: 1
      Index1: 1
      IndexAssignmentsA: [0, 3, 2]
      IndexAssignmentsB: [3, 1, 2]
      IndexAssignmentsLD: [4, 5, 6, 7]
      IndexUnroll: 3
      IndexUnrollA: 1
      IndexUnrollB: 0
      IndicesBatch: [2]
      IndicesFree: [0, 1]
      IndicesSummation: [3]
      NumIndicesBatch: 1
      NumIndicesC: 3
      NumIndicesFree: 2
      NumIndicesLD: 4
      NumIndicesSummation: 1
      OperationType: GEMM
      SetConstStrideA: []
      SetConstStrideB: []
      SilentHighPrecisionAccumulate: false
      TLUA: true
      TLUB: false
      Tensor0: 0
      Tensor1: 1
      TileA: 0
      TileAwareSelection: false
      TileB: 1
      TotalIndices: 4
      TransposeA: false
      TransposeB: false
      UseBeta: true
      UseInitialStrides: false
      ZeroPadA: []
      ZeroPadB: []
    ReplacementKernel: false
    ScheduleGlobalRead: 1
    ScheduleIterAlg: 1
    ScheduleLocalWrite: 1
    SolutionIndex: 2
    SolutionNameMin: Cijk_Ailk_Bljk_SB_MT16x32x32_SE_EPS1_FL1_GRVW4_NLCA1_PGR1_PLR1_TT2_2_USFGRO0_VW2_WGM8
    StaggerU: 32
    StaggerUMapping: 0
    StaggerUStride: 256
    SubGroup0: 8
    SubGroup1: 16
    SubGroupA: 8
    SubGroupB: 16
    SuppressNoLoadLoop: false
    ThreadTile: [2, 2]
    ThreadTile0: 2
    ThreadTile1: 2
    ThreadTileA: 2
    ThreadTileB: 2
    UnrollMemFence: false
    UseSgprForGRO: false
    Valid: true
    VectorAtomicWidth: 1
    VectorStore: true
    VectorWidth: 2
    WorkGroup: [8, 16, 2]
    WorkGroupMapping: 8
    WorkGroupMappingType: B
    _staggerStrideShift: 1
    fractionalPerpOverhangA: 0
    fractionalPerpOverhangB: 0
- [2, 3, 0, 1]
- - - [65, 6400, 1, 1024, 65, 65, 65, 1024]
    - [0, 1340.78]
  - - [1024, 64, 1, 4096, 1024, 1024, 1024, 4096]
    - [2, 2608.89]
  - - [256, 6400, 1, 4096, 256, 256, 256, 4096]
    - [1, 4231.98]
- null
