GlobalParameters: {CMakeBuildType: Release, DataInitTypeAB: 0, DataInitTypeBeta: 1, Device: 0, EnqueuesPerSync: 1, ForceRedoBenchmarkProblems: true, ForceRedoLibraryClient: true, ForceRedoLibraryLogic: true, KernelTime: true, LibraryPrintDebug: false, MergeFiles: true, MinimumRequiredVersion: 4.2.0, NewClient: 2, NumElementsToValidate: 0, PinClocks: false, Platform: 0, PrintSolutionRejectionReason: true, PrintWinnersOnly: 1, ShortNames: false, SleepPercent: 50, SolutionSelectionAlg: 1, SyncsPerBenchmark: 1, ValidationMaxToPrint: 4, ValidationPrintValids: false}
BenchmarkProblems:
- - {Batched: true, DataType: s, OperationType: GEMM, TransposeA: true, TransposeB: false,
    UseBeta: true}
  - BenchmarkCommonParameters:
    - EdgeType: [ShiftPtr]
    - KernelLanguage: [Assembly]
    - LoopTail: [true]
    - VectorWidth: [-1]
    - FractionalLoad: [1]
    - PrefetchLocalRead: [true]
    - PrefetchGlobalRead: [true]
    BenchmarkFinalParameters:
    - ProblemSizes:
      - Exact: [101, 100, 1, 512, 101, 101, 512, 512]
      - Exact: [64, 128, 1, 3136, 64, 64, 3136, 3136]
    BenchmarkForkParameters: null
    BenchmarkJoinParameters: null
    ForkParameters:
    - WorkGroupMapping: [1, 8]
    - DepthU: [8, 16, 24, 32]
    - GlobalSplitU: [1, 16]
    - TransposeLDS: [0, 1]
    - ThreadTile:
      - [4, 4]
      - [4, 6]
      - [6, 4]
      - [4, 8]
      - [8, 4]
      - [8, 8]
    - WorkGroup:
      - [16, 16, 1]
      - [8, 16, 2]
      - [16, 8, 2]
      - [4, 16, 4]
      - [16, 4, 4]
      - [8, 8, 4]
    InitialSolutionParameters: null
    JoinParameters: null
  - BenchmarkCommonParameters:
    - EdgeType: [ShiftPtr]
    - KernelLanguage: [Assembly]
    - LoopTail: [true]
    - VectorWidth: [-1]
    - FractionalLoad: [1]
    - PrefetchLocalRead: [true]
    - PrefetchGlobalRead: [true]
    BenchmarkFinalParameters:
    - ProblemSizes:
      - Exact: [101, 8, 1, 512, 101, 101, 512, 512]
    BenchmarkForkParameters: null
    BenchmarkJoinParameters: null
    ForkParameters:
    - WorkGroupMapping: [1, 8]
    - DepthU: [8, 16, 24, 32]
    - GlobalSplitU: [1, 16]
    - TransposeLDS: [0, 1]
    - ThreadTile:
      - [2, 2]
      - [4, 2]
      - [2, 4]
      - [4, 4]
    - WorkGroup:
      - [16, 16, 1]
      - [8, 16, 2]
      - [16, 8, 2]
      - [32, 8, 4]
      - [8, 32, 4]
      - [8, 8, 4]
    InitialSolutionParameters: null
    JoinParameters: null
  - BenchmarkCommonParameters:
    - EdgeType: [ShiftPtr]
    - KernelLanguage: [Assembly]
    - LoopTail: [true]
    - VectorWidth: [-1]
    - GlobalSplitU: [1]
    - FractionalLoad: [1]
    - PrefetchLocalRead: [true]
    - PrefetchGlobalRead: [true]
    BenchmarkFinalParameters:
    - ProblemSizes:
      - Exact: [128, 256, 1, 392, 128, 128, 392, 392]
      - Exact: [256, 512, 1, 49, 256, 256, 49, 49]
    BenchmarkForkParameters: null
    BenchmarkJoinParameters: null
    ForkParameters:
    - WorkGroupMapping: [1, 8]
    - DepthU: [8, 16, 24, 32]
    - TransposeLDS: [0, 1]
    - ThreadTile:
      - [4, 4]
      - [4, 6]
      - [6, 4]
      - [4, 8]
      - [8, 4]
      - [8, 8]
    - WorkGroup:
      - [16, 16, 1]
      - [8, 16, 2]
      - [16, 8, 2]
      - [8, 8, 4]
    InitialSolutionParameters: null
    JoinParameters: null
  - BenchmarkCommonParameters:
    - EdgeType: [ShiftPtr]
    - KernelLanguage: [Assembly]
    - LoopTail: [true]
    - VectorWidth: [-1]
    - FractionalLoad: [1]
    - PrefetchLocalRead: [true]
    - PrefetchGlobalRead: [true]
    BenchmarkFinalParameters:
    - ProblemSizes:
      - Exact: [1728, 128, 1, 3136, 1728, 1728, 3136, 3136]
      - Exact: [1728, 64, 1, 25088, 1728, 1728, 25088, 25088]
      - Exact: [441, 64, 1, 25088, 441, 441, 25088, 25088]
    BenchmarkForkParameters: null
    BenchmarkJoinParameters: null
    ForkParameters:
    - WorkGroupMapping: [1, 8]
    - DepthU: [8, 16, 24, 32]
    - GlobalSplitU: [1, 8, 16]
    - TransposeLDS: [0, 1]
    - ThreadTile:
      - [4, 4]
      - [4, 6]
      - [6, 4]
      - [4, 8]
      - [8, 4]
      - [8, 8]
    - WorkGroup:
      - [16, 16, 1]
      - [8, 16, 2]
      - [16, 8, 2]
      - [8, 8, 4]
    InitialSolutionParameters: null
    JoinParameters: null
  - BenchmarkCommonParameters:
    - EdgeType: [ShiftPtr]
    - KernelLanguage: [Assembly]
    - LoopTail: [true]
    - VectorWidth: [-1]
    - GlobalSplitU: [1]
    - FractionalLoad: [1]
    - PrefetchLocalRead: [true]
    - PrefetchGlobalRead: [true]
    BenchmarkFinalParameters:
    - ProblemSizes:
      - Exact: [13824, 512, 1, 49, 13824, 13824, 49, 49]
      - Exact: [3456, 256, 1, 392, 3456, 3456, 392, 392]
      - Exact: [6912, 256, 1, 392, 6912, 6912, 392, 392]
      - Exact: [6912, 512, 1, 49, 6912, 6912, 49, 49]
    BenchmarkForkParameters: null
    BenchmarkJoinParameters: null
    ForkParameters:
    - WorkGroupMapping: [1, 8]
    - DepthU: [8, 16, 24, 32]
    - TransposeLDS: [0, 1]
    - ThreadTile:
      - [4, 4]
      - [6, 4]
      - [4, 6]
      - [4, 8]
      - [8, 4]
      - [8, 8]
    - WorkGroup:
      - [16, 16, 1]
      - [16, 8, 2]
      - [8, 16, 2]
      - [8, 8, 4]
    InitialSolutionParameters: null
    JoinParameters: null
  - BenchmarkCommonParameters:
    - EdgeType: [ShiftPtr]
    - KernelLanguage: [Assembly]
    - LoopTail: [true]
    - VectorWidth: [-1]
    - FractionalLoad: [1]
    - PrefetchLocalRead: [true]
    - PrefetchGlobalRead: [true]
    BenchmarkFinalParameters:
    - ProblemSizes:
      - Exact: [3456, 128, 1, 3136, 3456, 3456, 3136, 3136]
    BenchmarkForkParameters: null
    BenchmarkJoinParameters: null
    ForkParameters:
    - WorkGroupMapping: [1, 8]
    - DepthU: [8, 16, 24, 32]
    - GlobalSplitU: [1, 4]
    - TransposeLDS: [0, 1]
    - ThreadTile:
      - [4, 4]
      - [6, 4]
      - [4, 6]
      - [4, 8]
      - [8, 4]
      - [8, 8]
    - WorkGroup:
      - [16, 16, 1]
      - [16, 8, 2]
      - [8, 16, 2]
      - [8, 8, 4]
    InitialSolutionParameters: null
    JoinParameters: null
LibraryLogic:
  ArchitectureName: gfx906
  DeviceNames: [Device 66a0, Device 66a1, Device 66a7, Device 66af, Vega 20]
  ScheduleName: vega20
LibraryClient:
