- {MinimumRequiredVersion: 4.9.11}
- vega20
- gfx906
- [Device 66a0, Device 66a1, Device 66a7, Vega 20]
- AssignedDerivedParameters: true
  Batched: true
  ComplexConjugateA: false
  ComplexConjugateB: false
  ComputeDataType: 0
  DataType: 0
  DestDataType: 0
  HighPrecisionAccumulate: false
  Index0: 0
  Index01A: 0
  Index01B: 1
  Index1: 1
  IndexAssignmentsA: [3, 0, 2]
  IndexAssignmentsB: [3, 1, 2]
  IndexAssignmentsLD: [4, 5, 6, 7]
  IndexUnroll: 3
  IndexUnrollA: 0
  IndexUnrollB: 0
  IndicesBatch: [2]
  IndicesFree: [0, 1]
  IndicesSummation: [3]
  NumIndicesBatch: 1
  NumIndicesC: 3
  NumIndicesFree: 2
  NumIndicesLD: 4
  NumIndicesSummation: 1
  OperationType: GEMM
  SilentHighPrecisionAccumulate: false
  TLUA: false
  TLUB: false
  Tensor0: 0
  Tensor1: 1
  TileA: 0
  TileB: 1
  TotalIndices: 4
  TransposeA: true
  TransposeB: false
  UseBeta: true
  UseInitialStrides: false
- - AggressivePerfMode: 1
    AssertFree0ElementMultiple: 1
    AssertFree1ElementMultiple: 1
    AssertMinApproxSize: 3
    AssertSummationElementMultiple: 1
    AssignedDerivedParameters: false
    AssignedProblemIndependentDerivedParameters: true
    BufferLoad: true
    BufferStore: true
    CheckDimOverflow: 0
    CheckTensorDimAsserts: false
    DepthU: 16
    DirectToLds: false
    DirectToLdsA: false
    DirectToLdsB: false
    DisableKernelPieces: 0
    EdgeType: ShiftPtr
    ExpandPointerSwap: true
    FractionalLoad: 0
    GlobalLoadVectorWidthA: 4
    GlobalLoadVectorWidthB: 4
    GlobalRead2A: true
    GlobalRead2B: true
    GlobalReadCoalesceGroupA: true
    GlobalReadCoalesceGroupB: true
    GlobalReadCoalesceVectorA: true
    GlobalReadCoalesceVectorB: true
    GlobalReadVectorWidth: 4
    GlobalSplitU: 1
    GlobalSplitUSummationAssignmentRoundRobin: true
    GlobalSplitUWorkGroupMappingRoundRobin: false
    GlobalWriteVectorWidth: 4
    GuaranteeNoPartialA: true
    GuaranteeNoPartialB: true
    InnerUnroll: 1
    InterleaveAlpha: 0
    KernelLanguage: Assembly
    LSCA: 16
    LSCB: 16
    LSPA: 64
    LSPB: 64
    LVCA: 4
    LVCB: 4
    LVPA: 16
    LVPB: 16
    LdcEqualsLdd: true
    LdsNumElements: 4096
    LdsNumElementsAlignedA: 1024
    LdsNumElementsAlignedB: 1024
    LdsOffsetA: 0
    LdsOffsetA_Blk: 2048
    LdsOffsetB: 1024
    LdsOffsetB_Blk: 3072
    LdsPadA: 0
    LdsPadB: 0
    LocalDotLayout: 1
    LocalRead2A: true
    LocalRead2B: true
    LocalSplitU: 1
    LocalWrite2A: true
    LocalWrite2B: true
    LocalWriteUseSgprA: false
    LocalWriteUseSgprB: false
    LoopDoWhile: false
    LoopTail: true
    LoopUnroll: 16
    MacroTile0: 64
    MacroTile1: 64
    MacroTileA: 64
    MacroTileB: 64
    MacroTileShapeMax: 64
    MacroTileShapeMin: 1
    MaxOccupancy: 40
    MinGlobalWriteVectorWidth: 1
    NonTemporalA: 0
    NonTemporalB: 0
    NonTemporalC: 0
    NumElementsPerThread: 16
    NumGlobalWriteVectorsPerThread: 4
    NumLoadsA: 1
    NumLoadsB: 1
    NumLoadsCoalescedA: 1
    NumLoadsCoalescedB: 1
    NumLoadsPerpendicularA: 1
    NumLoadsPerpendicularB: 1
    NumThreads: 256
    OptNoLoadLoop: 1
    PackBatchDims: 0
    PackFreeDims: 1
    PackGranularity: 2
    PackedC0Indices: [I]
    PackedC1Indices: [J]
    PerformanceSyncLocation: -1
    PerformanceWaitCount: -1
    PerformanceWaitLocation: -1
    PersistentKernel: 0
    PrefetchAcrossPersistent: 0
    PrefetchGlobalRead: true
    PrefetchLocalRead: true
    ProblemType:
      AssignedDerivedParameters: true
      Batched: true
      ComplexConjugateA: false
      ComplexConjugateB: false
      ComputeDataType: 0
      DataType: 0
      DestDataType: 0
      HighPrecisionAccumulate: false
      Index0: 0
      Index01A: 0
      Index01B: 1
      Index1: 1
      IndexAssignmentsA: [3, 0, 2]
      IndexAssignmentsB: [3, 1, 2]
      IndexAssignmentsLD: [4, 5, 6, 7]
      IndexUnroll: 3
      IndexUnrollA: 0
      IndexUnrollB: 0
      IndicesBatch: [2]
      IndicesFree: [0, 1]
      IndicesSummation: [3]
      NumIndicesBatch: 1
      NumIndicesC: 3
      NumIndicesFree: 2
      NumIndicesLD: 4
      NumIndicesSummation: 1
      OperationType: GEMM
      SilentHighPrecisionAccumulate: false
      TLUA: false
      TLUB: false
      Tensor0: 0
      Tensor1: 1
      TileA: 0
      TileB: 1
      TotalIndices: 4
      TransposeA: true
      TransposeB: false
      UseBeta: true
      UseInitialStrides: false
    ReplacementKernel: false
    ScheduleGlobalRead: 1
    ScheduleIterAlg: 1
    ScheduleLocalWrite: 1
    SolutionIndex: 0
    SolutionNameMin: Cijk_Alik_Bljk_SB_MT64x64x16_SE_EPS1_FL0_GRVW4_GSU1_PGR1_PLR1_TT4_4_VW4_WG16_16_1_WGM8
    StaggerU: 32
    StaggerUMapping: 0
    StaggerUStride: 256
    SubGroup0: 16
    SubGroup1: 16
    SubGroupA: 16
    SubGroupB: 16
    SuppressNoLoadLoop: false
    ThreadTile: [4, 4]
    ThreadTile0: 4
    ThreadTile1: 4
    ThreadTileA: 4
    ThreadTileB: 4
    UnrollMemFence: false
    UseSgprForGRO: 1
    Valid: true
    VectorAtomicWidth: 1
    VectorStore: true
    VectorWidth: 4
    WorkGroup: [16, 16, 1]
    WorkGroupMapping: 8
    WorkGroupMappingType: B
    _staggerStrideShift: 2
  - AggressivePerfMode: 1
    AssertFree0ElementMultiple: 1
    AssertFree1ElementMultiple: 1
    AssertMinApproxSize: 3
    AssertSummationElementMultiple: 1
    AssignedDerivedParameters: false
    AssignedProblemIndependentDerivedParameters: true
    BufferLoad: true
    BufferStore: true
    CheckDimOverflow: 0
    CheckTensorDimAsserts: false
    DepthU: 8
    DirectToLds: false
    DirectToLdsA: false
    DirectToLdsB: false
    DisableKernelPieces: 0
    EdgeType: ShiftPtr
    ExpandPointerSwap: true
    FractionalLoad: 1
    GlobalLoadVectorWidthA: 4
    GlobalLoadVectorWidthB: 2
    GlobalRead2A: true
    GlobalRead2B: true
    GlobalReadCoalesceGroupA: true
    GlobalReadCoalesceGroupB: true
    GlobalReadCoalesceVectorA: true
    GlobalReadCoalesceVectorB: true
    GlobalReadVectorWidth: 4
    GlobalSplitU: 1
    GlobalSplitUSummationAssignmentRoundRobin: true
    GlobalSplitUWorkGroupMappingRoundRobin: false
    GlobalWriteVectorWidth: 4
    GuaranteeNoPartialA: true
    GuaranteeNoPartialB: true
    InnerUnroll: 1
    InterleaveAlpha: 0
    KernelLanguage: Assembly
    LSCA: 8
    LSCB: 8
    LSPA: 128
    LSPB: 64
    LVCA: 2
    LVCB: 4
    LVPA: 32
    LVPB: 32
    LdcEqualsLdd: true
    LdsNumElements: 3584
    LdsNumElementsAlignedA: 1024
    LdsNumElementsAlignedB: 512
    LdsOffsetA: 0
    LdsOffsetA_Blk: 2048
    LdsOffsetB: 1024
    LdsOffsetB_Blk: 3072
    LdsPadA: 0
    LdsPadB: 0
    LocalDotLayout: 1
    LocalRead2A: true
    LocalRead2B: true
    LocalSplitU: 1
    LocalWrite2A: true
    LocalWrite2B: true
    LocalWriteUseSgprA: false
    LocalWriteUseSgprB: false
    LoopDoWhile: false
    LoopTail: true
    LoopUnroll: 8
    MacroTile0: 128
    MacroTile1: 64
    MacroTileA: 128
    MacroTileB: 64
    MacroTileShapeMax: 64
    MacroTileShapeMin: 1
    MaxOccupancy: 40
    MinGlobalWriteVectorWidth: 1
    NonTemporalA: 0
    NonTemporalB: 0
    NonTemporalC: 0
    NumElementsPerThread: 32
    NumGlobalWriteVectorsPerThread: 8
    NumLoadsCoalescedA: 1
    NumLoadsCoalescedB: 1
    NumLoadsPerpendicularA: 1
    NumLoadsPerpendicularB: 1
    NumThreads: 256
    OptNoLoadLoop: 1
    PackBatchDims: 0
    PackFreeDims: 1
    PackGranularity: 2
    PackedC0Indices: [I]
    PackedC1Indices: [J]
    PerformanceSyncLocation: -1
    PerformanceWaitCount: -1
    PerformanceWaitLocation: -1
    PersistentKernel: 0
    PrefetchAcrossPersistent: 0
    PrefetchGlobalRead: true
    PrefetchLocalRead: true
    ProblemType:
      AssignedDerivedParameters: true
      Batched: true
      ComplexConjugateA: false
      ComplexConjugateB: false
      ComputeDataType: 0
      DataType: 0
      DestDataType: 0
      HighPrecisionAccumulate: false
      Index0: 0
      Index01A: 0
      Index01B: 1
      Index1: 1
      IndexAssignmentsA: [3, 0, 2]
      IndexAssignmentsB: [3, 1, 2]
      IndexAssignmentsLD: [4, 5, 6, 7]
      IndexUnroll: 3
      IndexUnrollA: 0
      IndexUnrollB: 0
      IndicesBatch: [2]
      IndicesFree: [0, 1]
      IndicesSummation: [3]
      NumIndicesBatch: 1
      NumIndicesC: 3
      NumIndicesFree: 2
      NumIndicesLD: 4
      NumIndicesSummation: 1
      OperationType: GEMM
      SilentHighPrecisionAccumulate: false
      TLUA: false
      TLUB: false
      Tensor0: 0
      Tensor1: 1
      TileA: 0
      TileB: 1
      TotalIndices: 4
      TransposeA: true
      TransposeB: false
      UseBeta: true
      UseInitialStrides: false
    ReplacementKernel: false
    ScheduleGlobalRead: 1
    ScheduleIterAlg: 1
    ScheduleLocalWrite: 1
    SolutionIndex: 1
    SolutionNameMin: Cijk_Alik_Bljk_SB_MT128x64x8_SE_EPS1_FL1_GRVW4_GSU1_PGR1_PLR1_TT8_4_VW4_WG16_16_1_WGM1
    StaggerU: 32
    StaggerUMapping: 0
    StaggerUStride: 256
    SubGroup0: 16
    SubGroup1: 16
    SubGroupA: 16
    SubGroupB: 16
    SuppressNoLoadLoop: false
    ThreadTile: [8, 4]
    ThreadTile0: 8
    ThreadTile1: 4
    ThreadTileA: 8
    ThreadTileB: 4
    UnrollMemFence: false
    UseSgprForGRO: 1
    Valid: true
    VectorAtomicWidth: 1
    VectorStore: true
    VectorWidth: 4
    WorkGroup: [16, 16, 1]
    WorkGroupMapping: 1
    WorkGroupMappingType: B
    _staggerStrideShift: 3
    fractionalPerpOverhangA: 0
    fractionalPerpOverhangB: 0
  - AggressivePerfMode: 1
    AssertFree0ElementMultiple: 1
    AssertFree1ElementMultiple: 1
    AssertMinApproxSize: 3
    AssertSummationElementMultiple: 1
    AssignedDerivedParameters: false
    AssignedProblemIndependentDerivedParameters: true
    BufferLoad: true
    BufferStore: true
    CheckDimOverflow: 0
    CheckTensorDimAsserts: false
    DepthU: 16
    DirectToLds: false
    DirectToLdsA: false
    DirectToLdsB: false
    DisableKernelPieces: 0
    EdgeType: ShiftPtr
    ExpandPointerSwap: true
    FractionalLoad: 1
    GlobalLoadVectorWidthA: 2
    GlobalLoadVectorWidthB: 4
    GlobalRead2A: true
    GlobalRead2B: true
    GlobalReadCoalesceGroupA: true
    GlobalReadCoalesceGroupB: true
    GlobalReadCoalesceVectorA: true
    GlobalReadCoalesceVectorB: true
    GlobalReadVectorWidth: 4
    GlobalSplitU: 1
    GlobalSplitUSummationAssignmentRoundRobin: true
    GlobalSplitUWorkGroupMappingRoundRobin: false
    GlobalWriteVectorWidth: 4
    GuaranteeNoPartialA: true
    GuaranteeNoPartialB: true
    InnerUnroll: 1
    InterleaveAlpha: 0
    KernelLanguage: Assembly
    LSCA: 16
    LSCB: 16
    LSPA: 32
    LSPB: 64
    LVCA: 8
    LVCB: 4
    LVPA: 16
    LVPB: 16
    LdcEqualsLdd: true
    LdsNumElements: 4096
    LdsNumElementsAlignedA: 512
    LdsNumElementsAlignedB: 1024
    LdsOffsetA: 0
    LdsOffsetA_Blk: 2048
    LdsOffsetB: 512
    LdsOffsetB_Blk: 2560
    LdsPadA: 0
    LdsPadB: 0
    LocalDotLayout: 1
    LocalRead2A: true
    LocalRead2B: true
    LocalSplitU: 2
    LocalWrite2A: true
    LocalWrite2B: true
    LocalWriteUseSgprA: false
    LocalWriteUseSgprB: false
    LoopDoWhile: false
    LoopTail: true
    LoopUnroll: 8
    MacroTile0: 32
    MacroTile1: 64
    MacroTileA: 32
    MacroTileB: 64
    MacroTileShapeMax: 64
    MacroTileShapeMin: 1
    MaxOccupancy: 40
    MinGlobalWriteVectorWidth: 1
    NonTemporalA: 0
    NonTemporalB: 0
    NonTemporalC: 0
    NumElementsPerThread: 8
    NumGlobalWriteVectorsPerThread: 2
    NumLoadsCoalescedA: 1
    NumLoadsCoalescedB: 1
    NumLoadsPerpendicularA: 1
    NumLoadsPerpendicularB: 1
    NumThreads: 256
    OptNoLoadLoop: 1
    PackBatchDims: 0
    PackFreeDims: 1
    PackGranularity: 2
    PackedC0Indices: [I]
    PackedC1Indices: [J]
    PerformanceSyncLocation: -1
    PerformanceWaitCount: -1
    PerformanceWaitLocation: -1
    PersistentKernel: 0
    PrefetchAcrossPersistent: 0
    PrefetchGlobalRead: true
    PrefetchLocalRead: true
    ProblemType:
      AssignedDerivedParameters: true
      Batched: true
      ComplexConjugateA: false
      ComplexConjugateB: false
      ComputeDataType: 0
      DataType: 0
      DestDataType: 0
      HighPrecisionAccumulate: false
      Index0: 0
      Index01A: 0
      Index01B: 1
      Index1: 1
      IndexAssignmentsA: [3, 0, 2]
      IndexAssignmentsB: [3, 1, 2]
      IndexAssignmentsLD: [4, 5, 6, 7]
      IndexUnroll: 3
      IndexUnrollA: 0
      IndexUnrollB: 0
      IndicesBatch: [2]
      IndicesFree: [0, 1]
      IndicesSummation: [3]
      NumIndicesBatch: 1
      NumIndicesC: 3
      NumIndicesFree: 2
      NumIndicesLD: 4
      NumIndicesSummation: 1
      OperationType: GEMM
      SilentHighPrecisionAccumulate: false
      TLUA: false
      TLUB: false
      Tensor0: 0
      Tensor1: 1
      TileA: 0
      TileB: 1
      TotalIndices: 4
      TransposeA: true
      TransposeB: false
      UseBeta: true
      UseInitialStrides: false
    ReplacementKernel: false
    ScheduleGlobalRead: 1
    ScheduleIterAlg: 1
    ScheduleLocalWrite: 1
    SolutionIndex: 2
    SolutionNameMin: Cijk_Alik_Bljk_SB_MT32x64x16_SE_EPS1_FL1_GRVW4_GSU1_PGR1_PLR1_TT4_4_VW4_WG8_16_2_WGM1
    StaggerU: 32
    StaggerUMapping: 0
    StaggerUStride: 256
    SubGroup0: 8
    SubGroup1: 16
    SubGroupA: 8
    SubGroupB: 16
    SuppressNoLoadLoop: false
    ThreadTile: [4, 4]
    ThreadTile0: 4
    ThreadTile1: 4
    ThreadTileA: 4
    ThreadTileB: 4
    UnrollMemFence: false
    UseSgprForGRO: 1
    Valid: true
    VectorAtomicWidth: 1
    VectorStore: true
    VectorWidth: 4
    WorkGroup: [8, 16, 2]
    WorkGroupMapping: 1
    WorkGroupMappingType: B
    _staggerStrideShift: 2
    fractionalPerpOverhangA: 0
    fractionalPerpOverhangB: 0
- [2, 3, 0, 1]
- - - [2048, 512, 1, 100, 2048, 2048, 100, 100]
    - [1, 5180.71]
  - - [1024, 200, 1, 560, 1024, 1024, 560, 560]
    - [2, 4061.19]
  - - [1024, 512, 1, 1600, 1024, 1024, 1600, 1600]
    - [0, 7431.44]
- null
