          # Some configs from caffe2 std resnet
          - Exact: [  196,  256, 64, 1024 ]
          - Exact: [  196,  512, 64, 1024 ]
          - Exact: [  784,  512, 64,  128 ]
          - Exact: [  784,  128, 64,  512 ]
          - Exact: [  784,  256, 64,  512 ]
          - Exact: [   49,  512, 64, 2048 ]
          - Exact: [  196, 1024, 64,  256 ]
          - Exact: [   49, 2048, 64,  512 ]
          - Exact: [ 3136,  128, 64, 256 ]
          - Exact: [ 3136,   64, 64, 256 ]
          - Exact: [ 3136,  256, 64,  64 ]
          - Exact: [ 3136,   64, 64,  64 ]
